### ISSUE TITLE
南西海域およびマンスリー遠征データの登録

### ISSUE THREAD

**Issue by wifeofvillon** [KanCraft/kanColleWidget#1067]
現在idが未登録の遠征の一覧

- 拡張作戦(アルファベット始まり)に関しては[攻略Wiki](https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81#houshuu)のデータをそのまま持ってくることができない
- マンスリー遠征は月に1度しか成功させることができない

https://github.com/otiai10/kanColleWidget/blob/develop/src/js/Applications/Models/Queue/missions.ts

---

- [x] 南西方面連絡線哨戒
- [ ] 小笠原沖哨戒線
- [ ] 小笠原沖戦闘哨戒
- [x] 敵泊地強襲反撃作戦
- [ ] 南西諸島離島哨戒作戦
- [ ] 南西諸島離島防衛作戦
- [ ] 南西諸島捜索撃滅戦
- [x] ブルネイ泊地沖哨戒 (通常)
- [x] ミ船団護衛(一号船団)
- [ ] ミ船団護衛(二号船団)
- [ ] 航空装備輸送任務
- [x] ボーキサイト船団護衛 (通常)
- [x] 西方海域偵察作戦 (通常)
- [x] 西方潜水艦作戦
- [x] ラバウル方面艦隊進出

**Comment by wifeofvillon** [comment]
TODO: マンスリー遠征は15日にリセット

WIP: [【艦これ】定期任務 > missions - Google スプレッドシート](https://docs.google.com/spreadsheets/d/1F6gDmwzrKU6-QGqvA3Le1Jes7al7TtO8BR5RSrharvY/edit#gid=382951184)

**Comment by otiai10** [comment]
15日の午前4時は、まだ先月ですか？

**Comment by otiai10** [comment]
あ、これ遠征か。失礼。任務かと思いました。

**Comment by otiai10** [comment]
@wifeofvillon これはcloseですか？

**Comment by wifeofvillon** [comment]
closeします ユーザからの報告があれば新しく開きましょう
