### ISSUE TITLE
編成キャプチャのファイル名がスクショファイル名設定に従わない

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1105]
# 問題の概要

編成キャプチャをダウンロードすると，ファイル名が "編成キャプチャ_yyyyMMdd_HHmm" となり，
設定画面で「ダウンロードファイル名」に設定した値と異なります．
（「ダウンロードフォルダ」および「ファイル形式(jpeg/png)」の設定は反映されているようです）

「ダウンロードファイル名」に設定したファイル名になってほしいと思います．

# 環境

- OS: Windows10
- Chrome: 83
- 艦これウィジェット: 3.0.0-alpha.75

**Comment by otiai10** [comment]
これって、別途設定可能にしたほうがいいです？そこまでしなくていいです？

**Comment by xia-sava** [comment]
個人的には単一設定で困りません（v2 もそうでした）．

**Comment by otiai10** [comment]
#1125 で治ります
