### ISSUE TITLE
編成キャプチャの画像サイズが小さい

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1107]
# 問題の概要

編成キャプチャを撮ってダウンロードすると画像ファイルが妙に小さい……？

ウィンドウサイズ CLASSIC と ORIGINAL で試しましたが同じサイズになるようでした．

# 問題の再現方法

前提：ウィンドウサイズ自体は 1600x960

 - v3 通常スクショ → 1600x960
 - v2 通常スクショ → 1600x960
 - v3 編成キャプチャ → 576x673
 - v2 編成キャプチャ → 1926x2241
 - v2 編成キャプチャ 保存画面で1回縮小 → 1284x1494

保存画面での縮小機能（縦横サイズを 1.5 で割っている模様）はともかく，
v2 のキャプチャに近いサイズになるべきだと思います．

# 環境

- OS: Windows10 DPIスケーリング 200%
- Chrome: 83
- 艦これウィジェット: 2.1.9 / 3.0.0-alpha75

# 添付

v3 の，サイズが小さい編成キャプチャです．
![kancolle_20200714_153600](https://user-images.githubusercontent.com/679532/87394198-63773f80-c5ea-11ea-896d-5f8c9b789da4.jpeg)

**Comment by otiai10** [comment]
#1125 で治ります
