### ISSUE TITLE
提案) Releases にビルド済み zip を置いてはどうか

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1109]
提案ですが，GitHub の上のタブにある Releases のところで，
現状はソースコードの zip が得られるようになっていますが，
ここにビルド済みの zip （manifest と dest ディレクトリ入り）を置くようにして，
ビルド環境を作れない人でも v3 を試用できるようにする，というのはいかがでしょうか．

Releases の機能を自分で使ったことがないので，自動でそういうのが可能なのかどうかわからないんですけども……ｗ

**Comment by otiai10** [comment]
できるっぽいですね。やったことあるっぽいです。やってみます。
https://github.com/otiai10/amesh/blob/master/Makefile

**Comment by wifeofvillon** [comment]
https://github.com/otiai10/kanColleWidget/wiki/v3%E9%96%8B%E7%99%BA%E7%89%88%E4%BD%BF%E7%94%A8%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8BTips
このページにでもZIPから読み込む場合の手順書きましょうか

**Comment by otiai10** [comment]
@otiai10 

- https://github.com/actions/create-release
- https://github.com/actions/upload-release-asset

**Comment by wifeofvillon** [comment]
FYI: [v3開発版使用に関するTips > zipファイルをダウンロードして使用する方法 · otiai10/kanColleWidget Wiki](https://github.com/otiai10/kanColleWidget/wiki/v3%E9%96%8B%E7%99%BA%E7%89%88%E4%BD%BF%E7%94%A8%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8BTips#zip%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89%E3%81%97%E3%81%A6%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)

対応後用修正

**Comment by otiai10** [comment]
明日の定常リリースでどうなるか確認してからclose

**Comment by otiai10** [comment]
@wifeofvillon , @xia-sava 
できました
https://github.com/otiai10/kanColleWidget/releases/tag/3.0.0-alpha.77

**Comment by otiai10** [comment]
@wifeofvillon 
たぶんこのURLが便利だと思います
https://github.com/otiai10/kanColleWidget/releases/latest

Wiki編集していただけたらここcloseしちゃってください :bow:

**Comment by wifeofvillon** [comment]
リリースファイルのDL→読み込み→起動を確認し、手順をwikiに反映しました。お疲れ様でした

[v3開発版使用に関するTips · KanCraft/kanColleWidget Wiki](https://github.com/KanCraft/kanColleWidget/wiki/v3%E9%96%8B%E7%99%BA%E7%89%88%E4%BD%BF%E7%94%A8%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8BTips)
