### ISSUE TITLE
建造時間を誤認識する

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1118]
# 問題の概要

建造の完了時刻を誤認識することがわりとよくあります．

当方の環境で，建造時間 1:00:00 の時に OCR サーバに送信される画像がこちら：
![kancolle_OCR_010000_to_070000](https://user-images.githubusercontent.com/679532/87729467-664b7d80-c800-11ea-9a9d-ab678ec270a4.png)
これだと OCR は `7:00:00` を返しています．

上の方に見切れている赤線が良くないのかなと思って加工した画像がこちら：
![kancolle_OCR_010000_to_070000_2](https://user-images.githubusercontent.com/679532/87729485-719ea900-c800-11ea-8dce-b937b2b263d3.png)
これなら OCR が `1:00:00` を返します．

それぞれを base64 したデータで OCR を curl する sh の zip はこちら：
[repro.zip](https://github.com/KanCraft/kanColleWidget/files/4934698/repro.zip)

この赤線は画面上では砂時計アイコンの底の部分ですが，これを削るためにはキャプチャ位置を 2px 下にずらせば良さそうに思えます．

時刻表示の部分は環境ごとにフォントが異なるため，どの範囲が安全なのか自分の環境だけではわかりませんが，
さすがにフォント表示部と固定画像が被るような設計はしてなかろうと信じたいところです……

# 環境

- OS: Windows10
- Chrome: 84
- 艦これウィジェット: 3.0.0-alpha77

**Comment by otiai10** [comment]
@xia-sava , #1124 ご確認ください

**Comment by xia-sava** [comment]
すみません，今日のデイリー建造で試してみたところ，一番上のドックでは良さそうに見えたんですが，
2番目以降のドックで少しずつキャプチャ範囲がズレてしまっているようです．

2番目
![sb2](https://user-images.githubusercontent.com/679532/87889923-08709d00-ca6f-11ea-8837-5f07d2c748e5.png)

3番目
![sb3](https://user-images.githubusercontent.com/679532/87889924-09093380-ca6f-11ea-8827-d8fa6c6a89aa.png)

4番目
![sb4](https://user-images.githubusercontent.com/679532/87889925-09a1ca00-ca6f-11ea-87f4-8e193b19622d.png)

**Comment by otiai10** [comment]
うちの環境だとこうなるんすよね（デバッグモード on にしたときの画像です）
![image](https://user-images.githubusercontent.com/931554/87890724-969a5280-ca72-11ea-8fc7-d7297479758f.png)

**Comment by xia-sava** [comment]
わぁすいません，alpha.78 の環境でやってました！ alpha.79 の本件修正入りのバージョンでは大丈夫そうです！

:dogeza:

**Comment by otiai10** [comment]
よかったっす！
