### ISSUE TITLE
疲労タイマーがオフにできない

### ISSUE THREAD

**Issue by yutoki** [KanCraft/kanColleWidget#1128]
# 問題の概要
疲労タイマーを設定でオフにしても疲労タイマーがオフにならず、設定画面を再度開くとオンになっている

# 問題の再現方法

1. 設定画面から疲労回復をオフにする
（疲労タイマーのアイコン、通知オンは未設定。遠征のみ通知、通知音を設定している状態）

2.再度設定画面を開くと疲労回復がオンになっており、疲労通知が行われる

# 環境
OS: mac os 10.15
Chrome: 84
艦これウィジェット: 3.0.0-alpha80

**Comment by otiai10** [comment]
@otiai10 ソースコード確認したけど、この件かもしれない https://github.com/KanCraft/kanColleWidget/pull/1119

@yutoki オフにしようとしたときに、設定画面のコンソールにはどういうエラーが出てますか？

コンソールとは、ページで、右クリック→要素を検証→Consoleタブ選択、で出るやつです。画像参照

![image](https://user-images.githubusercontent.com/931554/88259356-6943e380-ccc2-11ea-9c3c-ae327f571e9c.png)

**Comment by otiai10** [comment]
CDのパイプラインでchomexが更新されてないのかな...

**Comment by yutoki** [comment]
![スクリーンショット 2020-07-23 16 00 44](https://user-images.githubusercontent.com/29172535/88259751-e3de2480-ccfd-11ea-9274-1850c65ae873.png)
これでどうでしょうか？

**Comment by otiai10** [comment]
まさにです！！ありがとうございます

**Comment by otiai10** [comment]
すべて判明しました。めちゃ助かりました

**Comment by otiai10** [comment]
@yutoki 一回完全にChrome拡張を削除して、もういちどストアからalpha80をインストールしてみてたらどうなりますかね

**Comment by yutoki** [comment]
再インストールしたらオフにできるようになりました

**Comment by otiai10** [comment]
よかったっす！
なんらかの理由で設定ページのソースコードが古かったんだと思います
