### ISSUE TITLE
バージョン3への要望 スクショ、通知、設定等

### ISSUE THREAD

**Issue by naoto-seki** [KanCraft/kanColleWidget#1134]
v3のリリースお疲れさまです。
いつも便利に使わせていただいております。
下記気になった点と機能要望を列挙させていただきます。

- スクショ機能について、一旦編集画面を挟まずDLする機能がほしい。
v2では直接指定フォルダにDLしていて、使い勝手が良かったので復活希望です。

- ウィンドウサイズを編集する項目がなくなっているので復活してほしい。
過去に設定したウィンドウサイズの情報は残っているようですが、新規で作成および編集ができる画面が見つかりませんでしが、どこかにあって私が見つけられていないだけであればすいません、無視してください。

- 任務受け忘れの通知もon/offできるようにしてほしい。
自分の使い方の問題ですが、基本通知系は全部オフで使っており、任務の通知もOFFにしたいです。

以上です、ご検討よろしくお願いいたします。

**Comment by otiai10** [comment]
ありがとうございます！フィードバックしてくれるだけで本当にたすかります。
3つの問題が内包しているので、3つに分けさせてもらいます。

**Comment by naoto-seki** [comment]
ありがとうございます。
お手数おかけしますがよろしくお願いいたします。
