### ISSUE TITLE
ウィンドウサイズ設定の追加編集設定

### ISSUE THREAD

**Issue by otiai10** [KanCraft/kanColleWidget#1136]
Close #1134

**Comment by SUGI017** [comment]
v3のリリースお疲れさまです&いつも使わせて頂きありがとうございます。

可能であれば、前回艦これウィジェット終了時のウインドウ位置とサイズを記憶し、復元する設定が欲しいです。
ご検討よろしくお願いします。

**Comment by otiai10** [comment]
これ必要なんかなー...？

**Comment by naoto-seki** [comment]
追記すいません。

個人的な使い方になってしまって申し訳ないんですが、
以前v2の時はサイズを75%に設定して使っており、その画面をアマレコというキャプチャソフトでキャプチャして実況動画の撮影を行っていました。

v3になってから、選択できる録画で使用できそうなサイズがOriginal(大きすぎる)とClassic(ちょっと小さい…)だけになってしまい、その中間がほしい感じです。

手動でウィンドウサイズを変えて運用すればいいのですが、
ふとした時に間違ってサイズを変更したりするときれいにサイズを戻すことが難しく、ウィジェット側で固定サイズを指定できると非常にありがたいです…

また、もしアドオンの設定ファイルを自前でいじって固定できるなどがあれば、該当箇所を教えてもらえれば個人で設定して使うのでそれでも問題ないかと思っています。

**Comment by xia-sava** [comment]
@naoto-seki 直接の解決ではない workaround ですが，Windows 環境であれば [ウィンドウ位置記憶アプリ](https://www.vector.co.jp/soft/win95/util/se401241.html) などを使ってサイズを自由に変更できます． 

v2 と違って v3 はウィンドウサイズの細かい変更にゲーム画面が完全に追従してくれるので，こういう外部アプリの使用が助けになるかもしれません．

**Comment by otiai10** [comment]
一応次のリリースで「前回のサイズを記憶」は実装されます

**Comment by naoto-seki** [comment]
@xia-sava 
ありがとうございます！
ご紹介いただいたアプリケーションでとりあえずやりたいことは対応できそうです！

@otiai10 
かしこまりました。
優先度かなり低めで構いませんので、頭の片隅に残しておいていただけると大変嬉しいです。
今後とも開発頑張ってください！
