### ISSUE TITLE
ミュート・スクショボタンの大小選択機能

### ISSUE THREAD

**Issue by nukopal** [KanCraft/kanColleWidget#1138]
UI周りの要望です。

画面右上に出るミュート・スクショボタンの大きさを変更できるとうれしいです。
(縮小表示している際、小さく感じる場合がある&以前の大きさがちょうどよいと感じているため)
設定画面に一項目追加いただけないでしょうか。場所は便利ボタンのグループ内でよいかと思います

**Comment by nukopal** [comment]
本文修正前に投稿してしまったため、修正して再Openします。

**Comment by otiai10** [comment]
以前の大きさってどんくらいでしたか？

**Comment by nukopal** [comment]
@otiai10 
横1080縦720、縮小率80%の状態で、スクショボタンの下端が母港画面右上のボーキの数字下端少し超えるくらいだったと思います。横幅はボーキ・鋼材の百の位～千の位の間だったような。
