### ISSUE TITLE
大破進撃防止機能が戦闘ごとに小さくなっていく

### ISSUE THREAD

**Issue by Snowsnowdawn** [KanCraft/kanColleWidget#1140]
# 問題の概要
連合艦隊で出撃したときの大破進撃防止窓（別窓表示）のサイズがどんどん小さくなっていく。

# 問題の再現方法

1.大破進撃防止窓の設定を別窓表示に
2. 連合艦隊で出撃（2020夏イベE6で確認）
3. 出撃ごとに大破進撃防止窓のサイズが小さくなる

手動で一度サイズ変えた後から発生するようになった気もしますが未検証……

# 問題が起きているバージョン

3.0.0-alpha.81

# 環境

- OS: Windows 10
- Chrome: 84.0.4147.105
- 艦これウィジェット: 3.0.0-alpha.81

# ひとこと

このリンクをみました 👉 http://amzn.asia/aWYh5Z0

**Comment by otiai10** [comment]
ここで対応済みです。3.0.1以降で治ったバージョンがリリースされると思います。3.0.1以降で確認できたらCloseしてください、

**Comment by Snowsnowdawn** [comment]
失礼しました。
ありがとうございます！

**Comment by otiai10** [comment]
音沙汰ないけどたぶん治ってるのでclose
