### ISSUE TITLE
スクショ保存ショートカットキー

### ISSUE THREAD

**Issue by yuuyuu0** [KanCraft/kanColleWidget#1141]
v3になって無くなってしまったようなのですが追加できませんか？

**Comment by wifeofvillon** [comment]
私自身がこの機能知らなかったのであれなんですけど、2.1.8でkeydownにバインドされているのはツイート関連の機能だけっぽいです。

2.1.7でも撮れないというツイートがあったので、もしかしたらもっと前にオミットされているかもしれません

https://twitter.com/trial_tomy/status/1292265772534751233

@yuuyuu0 この機能ってcmd+shift+0ないしctrl+shift+0でスクショを撮ったら直で画像がダウンロードされる機能だったって認識で合ってますか？

**Comment by wifeofvillon** [comment]
ちょっと一旦掘ってみますね

**Comment by xia-sava** [comment]
自分は ctrl+shift+0 のバインドでスクショ取ってましたね．デフォルトバインドがそんなんだったかと．

設定で「いったん加工画面で開く」みたいにしてたので，撮るたびに Chrome が（最小化してあっても）前面に来てしまっていた記憶がｗ

**Comment by wifeofvillon** [comment]
メモ:

- https://github.com/KanCraft/kanColleWidget/blob/1b3f96151f3c942726f4730dbfea16c35a12db97/manifest.json#L49
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands

**Comment by yuuyuu0** [comment]
@wifeofvillon
直に画像をダウンロードではなく、加工画面で開かれてました。
キーバインドも任意に変更できました。

**Comment by wifeofvillon** [comment]
Router完全にわからんので手離させてください 🙏
