### ISSUE TITLE
DEFAULT WHITEの初期画面サイズが小さい

### ISSUE THREAD

**Issue by Roadagain** [KanCraft/kanColleWidget#1142]
# 問題の概要

DEFAULT WHITEの画面サイズが小さくなっており、ゲーム画面がはみ出す状態になります
リサイズすると自動調整で戻ります

![無題](https://user-images.githubusercontent.com/7444623/89716235-46b20a00-d9e6-11ea-9cf6-1f7fe7f2bf1e.png)

# 問題の再現方法

1. DEFAULT WHITEモードで起動する

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.0-alpha.81
- 問題が観測されなかったバージョン: 2.x.x

# 環境

- OS: Windows
- Chrome: 84.0.4147.105
- 艦これウィジェット: 3.0.0-alpha.81

# ひとこと

ミスで中身が空のままsubmitしてしまいました、大変申し訳ないです

ウィンドウ作成時に渡されているsizeがouterHeight/outerWidthとして使われているようです
https://github.com/KanCraft/kanColleWidget/blob/b9661a020d1b2e92f15b02fd70bd50868265f4f6/src/js/Applications/Models/Frame.ts#L86-L93

![無題](https://user-images.githubusercontent.com/7444623/89716126-5c72ff80-d9e5-11ea-81ce-9a3e59eb168a.png)

chromeのapi docを読んだところ、widthとheightの部分は "including frame" と書かれていたので仕様だと思われます
https://developer.chrome.com/extensions/windows#method-create

このリンクをみました 👉 http://amzn.asia/aWYh5Z0

**Comment by otiai10** [comment]
v3で「DEFAULT WHITE」はなくなりました

**Comment by otiai10** [comment]
@Roadagain 「DEFAULT WHITE」っていう窓、まだ選択できてますか？

**Comment by Roadagain** [comment]
こちらではまだ確認できます
DEFAULT WHITEを開いてる途中に自動アップデートが入ったようなので、それが原因で残ったのかもしれません

![image](https://user-images.githubusercontent.com/7444623/89727058-81ef2000-da5c-11ea-908c-a9d3405e902d.png)
