### ISSUE TITLE
画面の拡大縮小ができるようにしてほしい

### ISSUE THREAD

**Issue by Niko25252** [KanCraft/kanColleWidget#1144]
お世話になっております。
以前までは、Ctrl +- や Ctrl マウスホイール　で、画面の拡大縮小が出来ていたと思いますが、v3になってこれを行っても自動で画面のサイズに合わさってしまうことが使いづらく感じます。この、自動で画面の大きさに合わさってしまう機能を、有効か無効にするかを選べるようにして欲しいです。

**Comment by otiai10** [comment]
「あえて余白がほしい」ってことですか？

**Comment by Niko25252** [comment]
そうですね
ウインドウ1つだけでその大きさを変えたり、Ctrl 0 などで戻したり出来たので重宝しておりました。

**Comment by otiai10** [comment]
@Niko25252 
どういう機能がほしいかちょっと絵描いてもらっていいですか？

**Comment by Niko25252** [comment]
以前ですと、このようにページの拡大縮小によって、今のバージョンよりも画面の大きさを楽に自分の好きなサイズに変えられたと思うのですが、現バージョンではウインドウの大きさに合うようになっていると思います。余白はこのようにあって良いです。個人的には以前のほうが使い勝手が良かったです。

[image: kan1.png]
[image: kan2.png]


2020年8月9日(日) 23:38 Hiromu OCHIAI <notifications@github.com>:

**Comment by otiai10** [comment]
@Niko25252 すみません、メールで返信すると添付画像が飛んでいっちゃうので、GitHubのissueページで画像をドラッグアンドドロップでお願いします

**Comment by Niko25252** [comment]
すみません。それに気づいて挙げなおしました。
以前ですと、このようにページの拡大縮小によって、今のバージョンよりも画面の大きさを楽に自分の好きなサイズに変えられたと思うのですが、現バージョンではウインドウの大きさに合うようになっていると思います。余白はこのようにあって良いです。個人的には以前のほうが使い勝手が良かったです。
![kan1](https://user-images.githubusercontent.com/20009138/89749053-29259300-db01-11ea-9788-daac11489d17.png)
![kan2](https://user-images.githubusercontent.com/20009138/89749054-2cb91a00-db01-11ea-92e8-0042e3ed9af1.png)

**Comment by otiai10** [comment]
下の画像の状態ができるようにしたい、ってことですか？

**Comment by Niko25252** [comment]
そうですね

**Comment by otiai10** [comment]
ちなみになぜですか？

**Comment by otiai10** [comment]
反応無いので閉じます。 #1136 でかいけつされると願って。
