### ISSUE TITLE
大破進軍防止窓の誤クリックを防止する対策

### ISSUE THREAD

**Issue by KnucklerO** [KanCraft/kanColleWidget#1145]
現状は画面遷移して自艦隊の表示が左に移動した直後を狙っていると思いますが、ほとんどの場合その後に経験値取得の時間が数秒間続くので、最大であと3秒程度？ディレイを長く出来ないでしょうか。
(理想は設定で早めと遅めを切り替えられるような形ですが)

うまく動作していないのはゲームが入力を受け付ける前にクリックしているのが原因だと思いますが、ディレイを長くすれば少しクリックが早い程度であれば対応できると思います。

また連合艦隊の場合の挙動ですが、第一艦隊のクリック受付から一定時間クリックを受け付けない時間が欲しいです。
これは自分の癖なのですが、たいていダブル(トリプル)クリックで操作してしまうので、第一艦隊が2枚表示されることが多々あるのです。

**Comment by otiai10** [comment]
「次」というボタンが表示されるまでの時間が環境依存である可能性があるので、入力を受け付けない時間を設定するのは設計としては正しくないと考えています。

**Comment by KnucklerO** [comment]
後半の要望に対する返答と解釈して話を続けます。
また環境による変化は今の所把握のしようがないので、私の環境における挙動や推測が含まれることはご了承ください。

「次」が表示される(第二艦隊の表示に進むクリックが受け付けられる)のは第一艦隊の経験値取得がすべて終わった後で、このクリックが入力されると第二艦隊の表示に移行するため、この時点で第一艦隊の撮影は終了していなければならないのではないでしょうか？
逆に言えば、第一艦隊の撮影が完了されるまでは第二艦隊のクリックは受け付けなくても問題ない(第一艦隊の撮影前に第二艦隊のクリックを受け付けて第二艦隊が正常に撮影される場合、第一艦隊の撮影に失敗している)と考えています。

**Comment by otiai10** [comment]
このChrome拡張はChrome拡張であるため、いろいろ技術的な制約があるんですけど、そのうちのひとつに「第一艦隊が表示された」「第二艦隊が表示された」というタイミングが**知りようがない**というものがあります。

それゆえに、現時点は「ユーザがクリックしたときは艦隊の状態が表示されているだろう」とする実装になっています。

わたくし落合の技術的な無知なのかもしれないので、おっしゃられるように具体的なアイデアをすでにお持ちであれば、ぜひPull-Requestを投げていただければと思います。勉強させていただきます。

**Comment by otiai10** [comment]
このあたりから掘るのがわかりやすいかと思います
https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Context/Features/DamageSnapshot.ts#L72-L83

**Comment by KnucklerO** [comment]
プログラミングはC言語での数値処理を少しかじった程度ですので、実際にコードを書くというようなことは私には荷が重いです、お力になれず申し訳有りません。

連合艦隊でのリザルト表示は以下のようになっていると思います。
①両軍の戦果ゲージ表示
②「勝利 S」等の表示
Ⅰ「次」表示(クリック待ち)
③第一艦隊のMVP表示、経験値取得  ←第一艦隊の撮影タイミング
Ⅱ「次」表示(クリック待ち)
④第二艦隊のMVP表示、経験値取得  ←第二艦隊の撮影タイミング
Ⅲ「次」表示(クリック待ち)
(終了)

その上で現在の実装は
・Ⅰ、Ⅱのクリックをトリガーとして、画面が切り替わる数秒を待った後に撮影する
・Ⅰのクリックは戦闘終了イベントの次のクリック、ⅡのクリックはⅠのクリックの次のクリックをそれと判断する
ものだと推測しています。(コードから読み取ったのではなく実際の挙動からの推測です。違っていればご指摘ください)

私が考えているのはⅡのクリックは③の表示が完了してから行われるものであるため、第一艦隊の撮影が完了する前(もしくはⅠのクリックから数秒間)に発生したクリックは全て無視していいのではないか、ということです。

(余談ですが要望の前半に関しては、現在③の期間の序盤に撮影しているものを、③の期間の中頃～終盤に変更できないかというものです。)

**Comment by otiai10** [comment]
すんません、要望を1行でまとめてもらっていいですか？

**Comment by KnucklerO** [comment]
分かりにくくてすみません
目的は「大破進軍防止窓の動作不良を無くして(減らして)ほしい」です

その上で比較的簡単に実現出来そうなものを提案しているつもりでしたが、一足飛びになっていました、失礼しました。

**Comment by otiai10** [comment]
![image](https://user-images.githubusercontent.com/931554/91148846-51aeaf00-e6f5-11ea-8fba-4f71e31c4659.png)

**Comment by otiai10** [comment]
うーん、やはりこれ、実装はできたものの「連打しないでください」のほうが正しい世界な気がしてきたな...

**Comment by ta-yamaoka** [comment]
動作を確認したところ現在バージョンと旧バージョン(3.0.0.65)では撮影するタイミング自体が異なっているように見えます
旧バージョンでは戦闘終了から一定時間経過後（？）に撮影しているのでしょうか？
戦闘中からResult画面を開く間中にずっとクリック連打していても撮影タイミングがずれることはありませんでした。

**Comment by otiai10** [comment]
3.0.0.65はかなり昔なのでソースコードを見る必要があります。

現在のバージョン（って3.0.9ですか？）で期待される挙動と、観察される挙動は何ですか？

**Comment by otiai10** [comment]
@ta-yamaoka 動作確認して頂いて、もうこれ治ったよ、っていうことでしたか？

**Comment by xia-sava** [comment]
(1) 戦闘終了後，しばらくユーザアクションを受け付けない時間が続きます
![kancolle_20200907_210839](https://user-images.githubusercontent.com/679532/92386236-5be99800-f14e-11ea-80a6-aa47525d1c07.jpeg)

(2) 戦闘結果表示と右下の [次] が表示されて，初めてユーザクリックを受け付ける状態になります
![kancolle_20200907_210842](https://user-images.githubusercontent.com/679532/92386266-6f94fe80-f14e-11ea-83ef-da3758bce16e.jpeg)

(3) 一定時間の後に自艦隊状況が表示されます
![kancolle_20200907_210844](https://user-images.githubusercontent.com/679532/92386321-8cc9cd00-f14e-11ea-824d-d9a847b549dc.jpeg)


艦これウィジェットは基本的にこの (2) の状態でのクリックを検出して，その一定時間後の (3) の画面から自艦隊状況を撮影します．
この挙動は v2 も v3 も根本的には同じだと思います．

いわゆる連打誤作動とされるものは，(2) を待たずに (1) の間にクリックすると，それを検出して (1) の途中の画面を取得してしまうことだと認識しています．

3.0.8 で実装されている処理は，この (1)～(2) までの間の一定期間にクリックを検出しないようにしているのだと思います（すみません，まだコード読んでません）．

3.0.8 で戦闘終了後から (1) の間ずっとひたすら連打していた時のスクショがこちらです．
![kancolle_20200907_211457](https://user-images.githubusercontent.com/679532/92386691-36a95980-f14f-11ea-80cc-0f23abd3197b.jpeg)
これを見る限り，意図した通りの挙動になっていると思います．
個人的には連打はしませんが，指先が震えてうっかりクリックとかを防げるので，とてもありがたい．

**Comment by ta-yamaoka** [comment]
@otiai10 
上記で述べている現在バージョンは、Ver3.0.6となります。
旧バージョンは、古いPCに入っていたもので正確にはVer2.1.9でした。

> 現在のバージョン（って3.0.9ですか？）で期待される挙動と、観察される挙動は何ですか？

クリック連打によって撮影タイミングがずれないでほしいです。
旧バージョンと同じ処理であれば問題ないと思っています。

> 動作確認して頂いて、もうこれ治ったよ、っていうことでしたか？

動作確認したのは、旧バージョンのものとなります。
こちらはクリックを連打していても、現在のように撮影タイミングがずれることはありませんでした。

**Comment by ta-yamaoka** [comment]
@otiai10
Ver3.0.6で再現確認用の動画を撮影しました。
戦闘中からリザルト画面を表示するまでずっとクリックしています。
[bandicam 2020-09-07 21-32-02-510.zip](https://github.com/KanCraft/kanColleWidget/files/5183121/bandicam.2020-09-07.21-32-02-510.zip)

**Comment by otiai10** [comment]
そうっすね。xiaさんが言っているように、v2とv3.0.7以前では、この挙動は同じです。つまり、どちらにしても慌てて連打してたら、艦隊が表示された状態のスクショは撮れません。これはv2でもv3.0.7以前でも変わりません。変わらないはずです。

なので、 @ta-yamaoka さんのおっしゃってる「差」とか「同じ処理であれば」は、何のことを言ってるのか僕は理解していません。

とはいえ、ご安心くだされ。 @xia-sava さんが言っているように、v3.0.8からは、艦隊被害状況が表示されるまでクリックを受け付けない親切実装が追加されました。

v3.0.8以降がリリースされたらご確認ください。

**Comment by ta-yamaoka** [comment]
@otiai10 
> v3.0.8以降がリリースされたらご確認ください。

了解です。

一応Ver2.1.9で撮影した動画も貼っておきます。
こちらも戦闘中からリザルト画面までずっとクリックしていますが、問題は発生しませんでした。
[bandicam 2020-09-07 21-40-49-931.zip](https://github.com/KanCraft/kanColleWidget/files/5183157/bandicam.2020-09-07.21-40-49-931.zip)

申し訳ありませんが、コードは読んでいません。
動きからV2とV2で動作が違うものと推測していました。

**Comment by otiai10** [comment]
今、2.1.8の実装確認して思い出したんですが、 @ta-yamaoka さんが正しいです。ごめんなさい。

v3系では、実装をシンプルにするために、大破進撃防止窓の仕組みを連合艦隊（クリック反応式）に一本化したんですよね。v2系では、通常艦隊は単なる時限式、連合艦隊はクリック反応式、という感じで2種類の実装を使ってたんです。なので、通常艦隊に限って言えば、 @ta-yamaoka さんのご指摘どおり、クリックに早急な誤反応はしないように見えたと思います。

不確かな記憶で反応してしまい申し訳ないです... 🙇 

いずれにしても、v3.0.8以降で良い感じになってると思います！！！！ 🙏
