### ISSUE TITLE
音声のみ、という通知設定がほしい

### ISSUE THREAD

**Issue by maruta00254** [KanCraft/kanColleWidget#1148]
V2では音声通知のみでポップアップは出さないという設定がありましたが
現状のV3では通知ポップアップが強制で出てくるようになっています
V2の設定にあった通知ポップアップを出すかどうかの設定を追加していただくことは可能でしょうか？

また、通知音の音量設定が出来ないのでそちらの設定もできるようにしていただけると幸いです

**Comment by otiai10** [comment]
@maruta00254 音声のみ、ってあります？「通知が自動的に消えるようにする」みたいなのはあったと思うんですけど。

**Comment by maruta00254** [comment]
![無題](https://user-images.githubusercontent.com/69394943/89805743-10ed5c80-db71-11ea-8d2e-55c9b401333d.png)

V2の通知設定の中に

・通知ポップアップを出す【音声通知は使うけど通知ポップアップはいらないというひと向け】

という項目があり、これをOFFにすることでポップアップを出さず音声のみでの通知が可能になっていました

**Comment by maruta00254** [comment]
@otiai10 

V2の通知設定の中に

・通知ポップアップを出す【音声通知は使うけど通知ポップアップはいらないというひと向け】

という項目があり、これをOFFにすることでポップアップを出さず音声のみでの通知が可能になっていました

![無題](https://user-images.githubusercontent.com/69394943/89805907-485c0900-db71-11ea-8d3d-2124f87435a7.png)

**Comment by otiai10** [comment]
なるほど。ありがとうございます。v2はソースコードが汚くてなんもメンテできなかったので、どういう仕様があったか教えていただけるととても助かります。

この件、やってみます。

**Comment by otiai10** [comment]
@maruta00254 これって、終了時の通知が自動で消えるようにすればだいたい同じような体験になったりしますかね？（妥協ラインをさぐってますｗ）

**Comment by maruta00254** [comment]
@otiai10 
できればポップアップを出さないというのが一番ありがたい所ではあります

 というのも全画面で他のゲーム等をプレイしていると通知のポップアップが邪魔になる事があり
音声のみでの通知というのが非常に助かっていたので、今回の機能要望を出させていただいた次第になります

もし、ポップアップの表示時間を短く設定できるのであれば一瞬表示してすぐ消えるのでそこまで邪魔にはならないかもしれないです


最終手段としてChromeの設定でウィジェットからの通知ポップアップをブロックして出ないようにするという方法もありますが
一度ブロックしてしまうとアプリの再インストール以外にブロックを解除する方法が無いため、あまりこの方法は使いたくないと考えています

**Comment by otiai10** [comment]
なるほど〜 妥当に必要っぽいっすね... やりましょう

**Comment by otiai10** [comment]
音量調節はもう実装したのでタイトル変えます
