### ISSUE TITLE
ポップアップにスクショボタンを追加してほしい

### ISSUE THREAD

**Issue by Shadow011240** [KanCraft/kanColleWidget#1149]
ダッシュボードにスクショボタンを追加して、
スクリーンショットを撮って「設定」の「スクショ設定」にある「ダウンロードフォルダ」に
直接保存できるようにしていただくことは可能でしょうか？

FAQの項目「スクリーンショットはどうやって撮れる？」に
「ダッシュボードの ⚓️ をクリックする」と記載されていますが、
ダッシュボードの ⚓️ をクリックすると、
画面の大きさがダッシュボードのリストボックス(「ORIGINAL」等)で指定している大きさに変わって、
スクリーンショットは撮れていないようです。
窓内スクショボタンの表示をONにしていてもOFFにしていても同じ動きになります。

**Comment by otiai10** [comment]
まず、ゲーム画面をどのように開いていますか？

**Comment by otiai10** [comment]
こういう状態になっていれば、ダッシュボードからスクショ撮れると思います
![image](https://user-images.githubusercontent.com/931554/89731263-888f8e80-da80-11ea-91ec-e93597b33ea5.png)

**Comment by otiai10** [comment]
タブから艦これのページを閉じて、ここの錨マークをクリックしてみてください。
![image](https://user-images.githubusercontent.com/931554/89731307-f471f700-da80-11ea-8787-dc1052f3689e.png)

**Comment by Shadow011240** [comment]
ダッシュボードの ⚓️ をクリックして起動しています。
リストボックスは「ORIGINAL」で、起動後に画面の大きさを手動で1期の時よりも少し大きい程度に調整しています。
![image](https://user-images.githubusercontent.com/46442673/89731309-f76ce780-da80-11ea-8759-901c83afdda1.png)

**Comment by otiai10** [comment]
その場合、開いているゲーム画面とダッシュボードが接続していない可能性があるので、いったんChromeブラウザを停止して再起動してみてください

**Comment by Shadow011240** [comment]
ゲーム画面とChromeブラウザを閉じて開き直してみます。

**Comment by wifeofvillon** [comment]
@Shadow011240 

> ダッシュボードの ⚓️ をクリックすると、
> 画面の大きさがダッシュボードのリストボックス(「ORIGINAL」等)で指定している大きさに変わって、

> ダッシュボードの ⚓️ をクリックして起動しています。

このあたりが気になったのですが、この時計の画面は開けていますか？

![ダッシュボード](https://user-images.githubusercontent.com/24819529/89726722-b82aa080-da58-11ea-9c12-fac5399da1d5.png)

**Comment by Shadow011240** [comment]
時計の画面は開いていない状態です。
時計マークを押すと表示はされます。
![image](https://user-images.githubusercontent.com/46442673/89731544-da391880-da82-11ea-9365-aaba54aec68f.png)

**Comment by Shadow011240** [comment]
ゲーム画面とChromeブラウザを閉じて開き直しましたが、錨のマークからはスクショできませんでした。
画面の大きさは変わりました。

**Comment by otiai10** [comment]
1. Chromeのプロセスをすべて完全に殺す（タスクバーから消す）
2. Chromeブラウザをひらく
3. 右上のアイコンからゲームをひらく（アドレスバーなどを含まない別窓）
4. 右上のアイコンからダッシュボードをひらく
5. ダッシュボードの錨マークを押す

をやってみてください。なお、手順3をしたあとのスクショをください。

**Comment by wifeofvillon** [comment]
ダッシュボード＝時計の画面です

**Comment by otiai10** [comment]
ダッシュボードのあそこ、カメラマークにしたほうがいいっぽいっすね @wifeofvillon

**Comment by otiai10** [comment]
および、このissueのタイトルはミスリーディングなので変えさせてもらいます

**Comment by Shadow011240** [comment]
手順3の結果
![image](https://user-images.githubusercontent.com/46442673/89731732-5aac4900-da84-11ea-8d04-c4b7a721df78.png)
手順4の結果
![image](https://user-images.githubusercontent.com/46442673/89731744-7152a000-da84-11ea-896c-be02076063cb.png)
手順5の結果　※スクショは撮れていない
![image](https://user-images.githubusercontent.com/46442673/89731782-b971c280-da84-11ea-86e1-bcf48798ec2e.png)

**Comment by Shadow011240** [comment]
画面起動後はカメラマークになっているとわかりやすいと思います。
issueのタイトル変更について承知いたしました。

**Comment by otiai10** [comment]
僕んとこだと、スクショ撮れますね。僕は通知アイコンを今「青春ブタ野郎はバニーガール先輩の夢を見ない」の麻衣先輩にしているので、ダッシュボードの錨マークは麻衣先輩ですが、ここをクリックすると撮れました。

**Comment by wifeofvillon** [comment]
ああ〜ダッシュボードの⚓️マーク(というか汎用通知マーク)は状態によって挙動が変わるんですね

- ウィンドウを開いていないとき→ウィンドウを開く
- ウィンドウを開いているとき→スクショ

知らんかった Wikiの記述を修正しておきます

**Comment by xia-sava** [comment]
（ダッシュボードアイコンって通知アイコンと連動だったのか……！！）

アイコンとは別に，インゲームボタンと同様な「スクショボタン」「ミュートボタン」がダッシュボードにあったらわかりやすいかもしれませんね．

**Comment by Shadow011240** [comment]
勘違いしていて、↓の画像(ポップアップ？)の錨マークばかり押していました…申し訳ありません。
![image](https://user-images.githubusercontent.com/46442673/89731956-32bde500-da86-11ea-829c-b5e5bc2944e9.png)

ダッシュボードの錨アイコンを押したら、スクショが撮れました。
お騒がせしました。これからはダッシュボードを開いて使用します。
![image](https://user-images.githubusercontent.com/46442673/89731974-5bde7580-da86-11ea-8def-e7f0436bd56c.png)

＞アイコンとは別に，インゲームボタンと同様な「スクショボタン」「ミュートボタン」がダッシュボードにあったらわかりやすいかもしれませんね．
あると助かります。

**Comment by otiai10** [comment]
あと「ポップアップ」とか「ダッシュボード」とかなんの気無しに言ってるの、伝わってないかもですね。
@Shadow011240 ありがとうございます、そのへんのわかりにくいところ、改善できると思います。これからもフィードバックください！

**Comment by Shadow011240** [comment]
よくわかっていなくて申し訳ありません…。
こちらこそ汲み取っていただき、ありがとうございます。
お手数ですが、よろしくお願いいたします。
