### ISSUE TITLE
ダッシュボードからスクショする錨マークがわかりにくいのでカメラマークにする

### ISSUE THREAD

**Issue by otiai10** [KanCraft/kanColleWidget#1150]
Related #1149

**Comment by otiai10** [comment]
- ゲーム画面があれば、カメラ
- ゲーム画面がなければ、錨

がいいかも？

**Comment by wifeofvillon** [comment]
@otiai10 

https://github.com/KanCraft/kanColleWidget/blob/7303314c8c25f95898289083a21ad87cb559b262/src/js/Applications/Components/Dashboard/ClockView/index.tsx#L59-L60

このへんで↓みたいにできるかと思ったのですがうまくいきませんでした

```
    this.client.message("/window/current-tab").then(res => {
      // ウィンドウが開かれていたらカメラ
      let icon = (res.status == 200) ? faCamera : faAnchor;
      return (
        <figure className="avatar avatar-xl bg-secondary" onClick={this.onClickIcon.bind(this)}>
          <FontAwesomeIcon icon={icon} />
        </figure>
      );
    });
```

**Comment by otiai10** [comment]
それは `renderIcon` 関数が`React.Element`を返すことが期待されているのに対して、上記のコードでは `then` の中のcallbackでreturnしているので、`renderIcon`の返り値として処理されていないからだと思います。

ロジックは正しいので、Reactっぽいコードを書く必要があると思います。

具体的には、親のComponentでsetIntervalみたいなことをしているはずなので、そこで `message("/window/current-tab")` を呼んで、stateに入れて、このComponentにはpropsとして渡す、っていう感じになると思います。

**Comment by otiai10** [comment]
親の `tick` っていう関数ですね。これをまず `private async tick` にして、その中で、

```js
const res = await client.message("/window/current-tab");
let icon = (res.status == 200) ? faCamera : faAnchor;

this.setState({
    // ...
});
```

みたいなことをすると思います
