### ISSUE TITLE
疲労回復ゲージの粒度をもう少し細かくしてほしい

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1157]
ダッシュボードの疲労回復ゲージ，3.0.0 では 1分単位でバーが表示されているのを，
もう少し細かく……10s単位くらいで表示してほしい．

「残り1分」なのか「残り10秒」なのかで，「じっと見て待つ」か「何か他のことする」か
けっこう変わることに，バー実装後に気付きました．

**Comment by otiai10** [comment]
@xia-sava これは、マウスオーバーして見えるというよりは、マウスオーバーせずに見えるバーの上のテキストに含めたほうがいいですか？

**Comment by xia-sava** [comment]
テキストでなくバー表示そのものが細かく変化してくれると嬉しいですね．

バー上のテキストは，文字色とサイズがちょっと見づらいので，現在はあまり参照していないです．
なので，バー上の表示は分単位でも個人的には問題ないと思います．

ホバーチップのテキストも，今はほぼ見ていません．
でもチップにだけ秒が表示されるとかなら，バーが残り1分（緑色）になってたらホバーして確認すればいいので，
そういう運用はいけそうな気がします．

**Comment by otiai10** [comment]
ん〜なるほど
