### ISSUE TITLE
ウインドウサイズを記憶する設定がほしい

### ISSUE THREAD

**Issue by SUGI017** [KanCraft/kanColleWidget#1158]
v3のリリースお疲れさまです&いつも使わせて頂きありがとうございます。

可能であれば、前回艦これウィジェット終了時のウインドウ位置とサイズを記憶し、復元する設定が欲しいです。
ご検討よろしくお願いします。

**Comment by otiai10** [comment]
位置は記憶されてるかなと思うんですが、どうですか？

**Comment by SUGI017** [comment]
されていないようです。普段は大型を画面右下端で開いているのですが、一旦閉じて開き直すと毎回中央左上寄りになります。
DEFAULT WHITEでも試したところ、こちらは毎回左上端で起動します。

**Comment by otiai10** [comment]
「DEFAULT WHITE」っていうのはv3では無くなったはずなので、お使いの環境がまだ完全にv3になってないみたいですね。

Chromeブラウザの再起動や、Chrome拡張の更新をためしてみてください。

**Comment by otiai10** [comment]
いずれにしても「サイズの記憶」は今実装してないので、やらなあかんのですが…

**Comment by SUGI017** [comment]
位置の記憶は拡張の更新で解決しました。失礼しました。
サイズの記憶の方もよろしくおねがいします。

**Comment by otiai10** [comment]
3.0.4で対応できると思います。
