### ISSUE TITLE
提案) How to Use v3ページの作成

### ISSUE THREAD

**Issue by wifeofvillon** [KanCraft/kanColleWidget#1164]
# 問題の概要

- そもそもウィジェットとして使うものだと知らないユーザーがいる
- ポップアップ、ダッシュボード、ゲーム内ボタンなどのざっくりUI名
- 編成キャプチャ機能など基本機能の使い方
- ショートカットキーなどの知っている人は知っている機能の使い方

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">基本的な使い方のWikiが必要かもしれない</p>&mdash; 艦これウィジェットちゃん (@KanColleWidget) <a href="https://twitter.com/KanColleWidget/status/1293141351316381697?ref_src=twsrc%5Etfw">August 11, 2020</a></blockquote>

# どうやってやるか

- Wikiにページを追加する
    - How to UseよりREADMEの方が通りはいいか？
    - 諸々の説明は私含めたユーザーが編集すればいいと思うのですが、コンセプトと方針については @otiai10 に追記して欲しいです

**Comment by wifeofvillon** [comment]
[v3の使い方 · KanCraft/kanColleWidget Wiki](https://github.com/KanCraft/kanColleWidget/wiki/v3%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9)

叩き台として見出しだけ置いてあります

**Comment by otiai10** [comment]
整理しました
https://github.com/KanCraft/kanColleWidget/wiki

**Comment by otiai10** [comment]
このissueはnever endingなのでいったんcloseします😇
