### ISSUE TITLE
大破進撃防止機能が機能しない

### ISSUE THREAD

**Issue by kntb-okk** [KanCraft/kanColleWidget#1168]
# 問題の概要

v3の公開お疲れ様です＆ありがとうございます。
大破進撃防止機能が正常に機能しないためご報告です。

# 問題の再現方法

1. 出撃する
　→1-1、2-2、2020夏イベE4、同E7で確認。通常艦隊／連合艦隊とも同様の状況。
2. 大破進撃防止窓の表示設定が「別窓表示」の時、画像のように艦隊状況が表示されない。
<img width="719" alt="無題" src="https://user-images.githubusercontent.com/69576727/90009585-4745eb80-dcd9-11ea-9793-81305e322e8e.png">
3. 大破進撃防止窓の表示設定が「ゲーム内表示」の時、窓自体が表示されない。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.3
　→3.0.0-alpha.81で初観測。
　　大破進撃防止機能が小さくなる問題といっしょに3.0.3で直ったりしないかな、と思っていましたがダメでした。

# 環境

- OS: Windows 10 Home
- Chrome: 84.0.4147.105
　→書いている途中でChromeが84.0.4147.125に更新されましたが、変化なしでした。

# ひとこと
マルチモニタ使ってる関係かな？と思い、接続切ってメインモニタの拡大率を150％→100％にしましたが、改善しません…

このリンクを見ましたが、もうちょっと目立つよう設定画面に置いてもいいのでは？
　 👉 http://amzn.asia/aWYh5Z0

**Comment by otiai10** [comment]
@kntb-okk ありがとうございます。

ゲーム窓が開いているときにバックグラウンドでChrome拡張がアップデートされると、ゲーム窓とChrome拡張のプロセスの接続が切れてしまい、ご指摘のような挙動になることが頻繁にあります。

なので、そのパターンもありうるかなと思っているので、Chrome自体を一度完全に殺してから、再度ゲーム窓をひらいて再現するかどうか確認いただけるでしょうか？

...という通知がアップデートされたときに出るようになってるはずなんだけど、動いてないのかな...？

**Comment by kntb-okk** [comment]
@otiai10  早速の返信、ありがとうございます。
Chromeを殺し、ウィジェットをいったん削除して入れなおし、PCを再起動し…と試したものの、残念ながらダメでした。
V3になってから、一度も大破進撃防止窓が使えていない状況なんですよね…
twitter見る限り他の方はちゃんと動いているようで「動いてへんのはお前だけ」状態っぽいのが辛いところ。

「拡張機能がアップデートされたので再起動を」といった通知は、少なくともV3になってからは見ていないです。

**Comment by otiai10** [comment]
@kntb-okk 窓内表示だと動きますか？

**Comment by kntb-okk** [comment]
@otiai10 窓内表示だと、大破進撃防止窓自体がそもそも表示されない状態です。画面左上にマウスオーバーしても変わらず。
他の拡張機能が悪さしてるかな？と思い、ウィジェット以外全て一旦切ってみましたがダメでした。

（設定画面の説明文では「窓内表示」で、プルダウンメニューでは「ゲーム内表示」なので、どっかの更新時で表記揃えた方が良いかも？）

**Comment by otiai10** [comment]
今のところ、当方の環境では再現されていません

**Comment by kntb-okk** [comment]
@otiai10 検証ありがとうございます。twitter上でも同様の症例が殆ど見受けられず、おま環案件だなぁ…

…と思っていたところ、ウィジェットちゃんが牡蠣ツイートをRT。
　https://twitter.com/pot534fog/status/1299359833435463685
これをもとに、Chrome側の設定を「サードパーティのCookieをブロックする」から「Cookieをすべて受け入れる」に変更したところ、正常に動作しました。

![image](https://user-images.githubusercontent.com/69576727/91589050-1087fa80-e994-11ea-93f3-35f6cd79987c.png)
SSはゲーム内表示ですが、別窓表示も正常に動作しています。
（また、Chrome側の設定を再び「サードパーティ～」に戻したところ、症状が再発しました）

動作確認バージョン：3.0.6

@wifeofvillon 表記統一のissue立て、ありがとうございました。

**Comment by otiai10** [comment]
治ってよかったっす！！！！ 勉強になりました

**Comment by otiai10** [comment]
FAQにリンクしたほうがいいかな
