### ISSUE TITLE
ウィジェット起動毎にミュートが解除される

### ISSUE THREAD

**Issue by naoto-seki** [KanCraft/kanColleWidget#1170]
# 問題の概要
ウィジェット起動毎にミュートが解除される。

- 期待される挙動
  - ミュート状態でウィンドを閉じた場合、再度ウィジェットを起動したときもミュート状態のままでいてほしい
- 実際に観測される挙動
  - ウィジェットを立ち上げ直したときアイコンはミュート状態を示しているが音が出る、ミュートボタンを2回押して再度ミュート状態にするとミュートになる。

# 問題の再現方法

1. ウィジェットを立ち上げる。
2. 画面右上のミュートボタンを押し、ミュート状態にする。
3. ウィンドを閉じ、再度ウィジェットを立ち上げる。
4. ミュートボタンを確認すると、ミュート状態になっているが、音が出ている。

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.3
- 問題が観測されなかったバージョン: ?
ほとんどウィンド立ち上げっぱなしなのであまり気が付かなかったが、
確かv2運用時も後半はそうなっていたので、自環境の問題かChrome側の問題の可能性もある。

# ひとこと
毎回オフにしなおせばいいので優先度は低めです。
あと別issue上がっているのであれですが、画面上のミュートとスクショのアイコンもうちょい大きいとうれしいです。

# 20.08.31追記
下記動作環境化で拡張機能をウィジェット以外削除した状態での動作を確認したところ、数回に1回は正常にミュートが継続する場合があることを確認。再現ができていないため、ウィンドを閉じてからの次の起動までのタイミングなどに依存する？

艦これウィジェット ver 3.0.6
Windows 10 pro 64bit(最新までアップデート済み)
バージョン: 85.0.4183.83（Official Build） （64 ビット）

**Comment by otiai10** [comment]
@wifeofvillon これは #1180 で治りますか？

**Comment by wifeofvillon** [comment]
@otiai10 #1180 はミュートボタン非表示設定のときにスクショボタンがエラーに巻き込まれるのを直しただけなので直らないと思います。

テスター向けリリース3.0.5で同様の手順を試しましたが再現しませんでした。(mac)

**Comment by yutoki** [comment]
こちらの環境で発生しています。
OSX
Chrome 84.0.4147.135
ウィジェットはver 3.0.6リリースバージョン

原因判明に繋がるかわかりませんがちょっと何パターンか試してみて

・起動時に音声オン→「か・ん・こ・れ」と言う前（ウィジェット起動してからゲーム音が一回も出ていない状態。タイトル画面でGAMESTARTを押すと言います。）でミュートにしても音が鳴ったままになります。
・起動時にミュート→GAMESTART前にミュート解除→GAMESTART前でもう一度ミュート→これでも音は鳴ります。
・起動時に音声オン→GAMESTART後、「か・ん・こ・れ」と言ってる間にミュート→ミュートになります。

同じようにウィジェット使わずにChromeから艦これを開いてサイトのミュート（タブを右クリック）を上と同じようにやってみましたが同じ結果でした。

**Comment by hokuhokuhog** [comment]
私も同じことが起きてます
解決になるかわかりませんがDMMの他ゲーム　フラワーナイトガールでも同様のことが起きます
Chromeの機能でサイトをミュートを使ってもゲーム開始するとタブにミュートマークが表示されたまま音声が再生されるため
DMMの一部ゲームの仕様なのかもしれません

**Comment by otiai10** [comment]
なるほど興味深いっすね。艦これウィジェット、ないしdemado（別のChrome拡張）を完全に削除しても、この問題は再現されますか？

**Comment by hokuhokuhog** [comment]
削除してやってみましたが再現されました
フラワーナイトガールの方だとメイン画面に現在の環境だと正常に作動しないという表示がでていて
セキュリティ関係で例外設定しろと表示されているため　WindowsDefender等の設定のせいなのかもしれません
ちなみに他のDMMゲーム　御城プロジェクト等ではサイトのミュートは正常に作動しています

**Comment by otiai10** [comment]
@naoto-seki @yutoki 
艦これウィジェット、ないしdemado（別のChrome拡張）を完全に削除しても、この問題は再現されるか試して頂いてもいいですか？

**Comment by naoto-seki** [comment]
艦これウィジェット以外の拡張を全てOFFでも再現しますが、何回かに1回は正常にミュートが継続されるようになりました…なんだこれ。

ミュートにしてウィンドを閉じる
立ち上げる→ミュート表示のまま音が出る。
再度ON/OFFを切り替えてミュートにする。
ウィジェットを落として立ち上げ直す→音がでないときもある。(何回に1回の割合は不明)

下記動作環境です。
Windows 10 pro 64bit(最新までアップデート済み) 
バージョン: 85.0.4183.83（Official Build） （64 ビット）

**Comment by otiai10** [comment]
ありがとうございます。
お時間あるときでかまいませんので、一番うえのissueの概要もアップデートしておいていただけると助かります。

**Comment by otiai10** [comment]
ここは、艦これウィジェット起因ではない、という結論でcloseしようと思うのですが、どうでしょうか

**Comment by PCEDuo** [comment]
この症状、起動直後にスピーカーアイコンをOFFにしても
艦これにログインするとまた解除されてるのが謎...

原因に関わるかかわからないが
最近、Chromeで日本語環境をONにしていても新しいタブではそれが反映されないという
状態になってて面倒(以前は反映されていた)
おそらくは仕様変更がなされたのだと思う。←この仕様が影響しているんでは？と
思わないでもない。

**Comment by otiai10** [comment]
これまだ再現しますか？クローズしようと思います
@naoto-seki @yutoki @PCEDuo @hokuhokuhog @wifeofvillon

**Comment by yutoki** [comment]
再現はしますが、対応は難しいと思われますのでクローズで大丈夫です。

**Comment by PCEDuo** [comment]
3.2.14 にて再現してる
その都度ミュートすればいいので

2021年1月6日(水) 13:03 Hiromu OCHIAI <notifications@github.com>:
