### ISSUE TITLE
ゲーム内便利ボタンで隠れて基地航空の解除ボタンが押せない

### ISSUE THREAD

**Issue by maruta00254** [KanCraft/kanColleWidget#1176]
すでにTwitterでウィジェットちゃんへの報告をされてる方もいましたが

今回のアップデートでゲーム内ミュート・スクショボタンの大きさが変更された為
演習のキャンセルボタンや、右側に出た基地航空の解除ボタンとミュート・スクショボタンが重なってしまう様になってしまいました

演習画面での便利ボタン位置
![無題1](https://user-images.githubusercontent.com/69394943/90310281-14933180-df2b-11ea-9425-6542c29a8cbd.png)

基地航空画面での便利ボタン位置
![無題](https://user-images.githubusercontent.com/69394943/90310212-8b7bfa80-df2a-11ea-9b01-ca5cf4ff2725.png)

演習のキャンセルは「×」を押さなくても前画面に戻れるのでそこまでの影響はないのですが
基地航空の解除は基地航空窓が固定され動かなくなっているので解除ボタンが押せないという状況になっています

**Comment by wifeofvillon** [comment]
#1177 でサイズ検討画像を作っていたんですが一旦4%くらいにしてしまった方が良いかもしれませんね

<img width="591" alt="スクリーンショット 2020-08-15 19 28 16" src="https://user-images.githubusercontent.com/24819529/90310565-8c625b80-df2d-11ea-8b27-72d84774db68.png">

とりあえずやってしまいます
