### ISSUE TITLE
ゲーム内便利ボタン表示設定の不具合

### ISSUE THREAD

**Issue by maruta00254** [KanCraft/kanColleWidget#1178]
便利ボタンの表示設定を
![無題3](https://user-images.githubusercontent.com/69394943/90310527-0fcf7d00-df2d-11ea-97e9-9194560ed3ba.png)
この様に設定した場合にゲーム内ボタンが表示されなくなってしまう

**Comment by wifeofvillon** [comment]
close 1179.

重複してしまったのでこっちに統一

**Comment by wifeofvillon** [comment]
前に同じことがあった #980
