### ISSUE TITLE
提案) Wikiの更新を艦これウィジェットちゃんに告知してもらう

### ISSUE THREAD

**Issue by wifeofvillon** [KanCraft/kanColleWidget#1184]
# 問題の概要

- Wikiに書いておいても読んでもらえないことがある
- Wikiは誰でも更新していいはずだけどそう認識されていない気がする
- Wikiの編集者が少ないと誤った記述があったとき修正が遅れる

など

# 参考

- [Webhook events and payloads - GitHub Docs](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#gollum)
- [GitHub ActionsでGitHub Wikiの更新情報(gollum)を取得する - Qiita](https://qiita.com/wifeofvillon/items/970ecb9794e03fee986d)

# ひとこと

そもそもGitHub Wikiを使い続けるのか？という話もあると思うので優先度は全然高くないです

**Comment by otiai10** [comment]
Wikiって誰でも編集できるんでしたっけ？

**Comment by wifeofvillon** [comment]
パブリックリポジトリはGitHubアカウント持ってれば誰でも更新できると思います(試したことないけど

**Comment by wifeofvillon** [comment]
> GitHub Wikis is a simple way to let others contribute content. Any GitHub user can create and edit pages to use for documentation, examples, support, or anything you wish. *...[Options](https://github.com/KanCraft/kanColleWidget/settings)*
