### ISSUE TITLE
CUSTOMで開いてもCLASSICの大きさになる

### ISSUE THREAD

**Issue by kotobukitakahashi** [KanCraft/kanColleWidget#1185]
# 問題の概要
画面サイズのプルダウンメニューの内容が保持されなくなりました。
- 期待される挙動
 前回自分で選択した内容が保持される。（例）ORIGINAL
- 実際に観測される挙動
 毎回CUSTOMが先頭に来て選択されています。
# 問題の再現方法
ウィジェットのアイコンをクリックする。
上記の方法により、100％の確率で、再現する。
# 問題が起きているバージョン
- 問題が観測されるバージョン: 3.0.5
- 問題が観測されなかったバージョン: 3.0.3
# 環境
- OS: Windows
- Chrome: 84.0.4147.125
- 艦これウィジェット: 3.0.5

# ひとこと
このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by otiai10** [comment]
CUSTOMのまま錨マークを押すとどうなりますか

**Comment by kotobukitakahashi** [comment]
前のORIGINALのサイズでウインドウが開き、その中でカスタムサイズと思われる小さいサイズで表示されますね。
自分のところだけでしょうか？

**Comment by otiai10** [comment]
問題のスクショいただいていいですか？

**Comment by kotobukitakahashi** [comment]
なにか設定を操作したかと思い、試してみたところ、現象が発生する条件がわかりました。
ミュートとスクショのボタンが大きくなったので、ミュートのボタンのみを表示オフにしたところこの現象が起こりました。
スクショボタンのみ表示オフ、、両方とも表示オフ、両方とも表示オンのときは正常に動作します。
よろしくお願いします。

**Comment by kotobukitakahashi** [comment]
一応、スクショです。CUSTOMの表示と書いてしまいましたが、プルダウンの先頭のORIGINALより小さいサイズ＝CLASSICのようです。
![スクリーンショット2020-08-16-161305](https://user-images.githubusercontent.com/29418480/90329059-621ba700-dfdc-11ea-8d4f-caf6cb8d1aef.png)
![スクリーンショット 2020-08-16 16 14 16](https://user-images.githubusercontent.com/29418480/90329060-647e0100-dfdc-11ea-94ed-026a881cff14.png)

**Comment by wifeofvillon** [comment]
> ミュートとスクショのボタンが大きくなったので、ミュートのボタンのみを表示オフにしたところこの現象が起こりました

これの修正をしているときに同じ事象に遭遇しました。ミュートボタンの表示設定のバグが他の要素に影響を及ぼしていたので、3.0.6で直るかもしれません。

@otiai10 2回目以降の起動でCUSTOMがデフォルト選択になるのは現状期待値通りですか？

**Comment by wifeofvillon** [comment]
related: #1178

**Comment by otiai10** [comment]
CUSTOMって名前が悪くて、あれ「前回起動時と同じ」って意味なんですけど、誰が命名したんだか...←
なので、popupのプルダウンにおいてCUSTOMがデフォルト選択になるのは期待通りです。

**Comment by kotobukitakahashi** [comment]
すみません、自分もその挙動に気づくの遅れてました。
なのでプルダウンメニューの挙動には問題なく、問題なのは、画面サイズが以前に選択したサイズではなく、おそらくプルダウンの先頭のCLASSICで起動してしまうことですね。
よろしくお願いいたします。

**Comment by wifeofvillon** [comment]
@kotobukitakahashi 3.0.6がリリースされたと思いますがその後どうでしょうか？
