### ISSUE TITLE
通知オフにしても通知音が鳴る

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1186]
# 問題の概要

通知設定でトグルスイッチをオフにしても通知音が鳴ります．

# 問題の再現方法

1. 設定画面から，建造通知を有効にして，通知音を設定する
2. 建造タイマーに手入力で 00:01 をセットする
3. 1分後に，建造完了通知が表示され，通知音が鳴る（←期待通りの動作
4. 設定画面から，トグルスイッチで建造通知を無効にする
5. 建造タイマーに手入力で 00:01 をセットする
6. 1分後に，建造完了通知は表示されないが，通知音が鳴る（←期待しない動作

おおむね，以下のような挙動のようです．

|             | 通知音あり | 通知音なし |
| ----------- | --------- | --------- |
| **通知有効** | 通知○ 音○ | 通知○ 音△ |
| **通知無効** | 通知× 音○ | 通知× 音△ |

※ △ ……「建造」通知音なしの設定の場合，「デフォルト」に通知音がセットされていればそれが鳴る（たぶん期待通りの動作）

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.6

# 環境

- OS: Windows10
- Chrome: 84.0.4147.125
- 艦これウィジェット: 3.0.6

**Comment by otiai10** [comment]
通知オフ && 通知音設定アリ、の場合は音だけ鳴るようにしたんですよね #1148 
UI作るのがめんどくさかったのでconfusingな設定になってしまいました... どうしよっかな
CC @maruta00254

**Comment by otiai10** [comment]
見かけ上「バグ」

**Comment by xia-sava** [comment]
あー「通知音設定」が自動的に「音を出すかどうか」のトグルになってるって仕組みだったんですね．
それならそういう仕様で個人的には挙動に納得です．

トグルの横に「通知を出す / 出さない」が判る表記，
通知音を設定するボタンの横に「音を出す / 無音」がわかる表記があれば，
視覚的に判りやすいのかな……？
