### ISSUE TITLE
タイマー手動セット時，既に登録済みの時刻が予め記入されていてほしい

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1187]
# 問題の概要

ダッシュボードの時刻表示をクリックして任意時刻を入力する時，
既に時刻が登録されているタイマーの時は，
その登録済み時刻が予め記入された状態であってほしい．

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.6

うろ覚えで申し訳ないですが，以前は記入されていたような……？

**Comment by otiai10** [comment]
たしかに最初の実装では記入されてるっぽいですね。
https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Components/Dashboard/QueuesView/MatrixView.tsx#L116

考えうるのは、この前`Date.prototype.upto`の返り値を変えたので、そのせいかもしれない？
