### ISSUE TITLE
クリック連打すると大破進撃防止窓が正しくキャプチャされない

### ISSUE THREAD

**Issue by ta-yamaoka** [KanCraft/kanColleWidget#1188]
# 問題の概要

- 期待される挙動
  - 大破進軍防止窓が正しくキャプチャされること
- 実際に観測される挙動
  - 大破進軍防止窓が正しくキャプチャされず、タイミングがずれた画像となる
以下の3枚が例となります

![image](https://user-images.githubusercontent.com/11879583/90372438-6236a800-e0ab-11ea-88a0-0bb89cd7b1ee.png) ![image](https://user-images.githubusercontent.com/11879583/90372599-990cbe00-e0ab-11ea-8a9e-b107e62247ff.png) ![image](https://user-images.githubusercontent.com/11879583/90371724-5991a200-e0aa-11ea-9b15-744bf2fa113f.png) 
# 問題の再現方法

1. 設定画面で「大破進撃防止窓の表示」を「ゲーム内表示」にする
2. 出撃して戦果報告画面まで進む
3. 戦果報告画面でクリックを連打する
4. 大破進軍防止窓のキャプチャされるタイミングがずれて正しい画像にならない

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.5
- 問題が観測されなかったバージョン: 3.0.0.65

# 環境

- OS: Windows 10 Pro 
バージョン 10.0.19041 ビルド 19041
- Chrome: 84.0.4147.125
- 艦これウィジェット: 3.0.5

# ひとこと

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by otiai10** [comment]
#1145 で議論されているので、そちらでコメントしてください。ここはcloseします。
