### ISSUE TITLE
[開発者向け] GitHub Actionsがforkしたリポジトリで走ってしまう対策

### ISSUE THREAD

**Issue by wifeofvillon** [KanCraft/kanColleWidget#1191]
# 問題の概要

リリースフローやmerge、エゴサなどのActionsがforkしたリポジトリ(ex. wifeofvillon/kanColleWidget)で走ってしまう

# 問題の再現方法

1. forkする
2. GitHubの設定を変えない

# 対策

<img width="885" alt="スクリーンショット 2020-08-20 13 19 57" src="https://user-images.githubusercontent.com/24819529/90716783-b24e7e00-e2e8-11ea-960a-2a4e5f2e6735.png">

Settings > Actions から設定を↑のように変える必要があることを[CONTRIBUTING.md](https://github.com/KanCraft/kanColleWidget/blob/develop/CONTRIBUTING.md)に記載する

(公式には↓みたいな記述もある)

> フォークされたリポジトリのワークフローは、デフォルトでは動作しません。 *[GitHub Actionsについて - GitHub Docs](https://docs.github.com/ja/actions/getting-started-with-github-actions/about-github-actions)*

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.6

**Comment by otiai10** [comment]
これってfork先のrepoで「走るけどSecretsは使えないからfailする」ってことですか？

**Comment by wifeofvillon** [comment]
@otiai10 secretsが使えないのでウィジェットちゃんがツイートしたりストアリリースしたりはないのですが、ローカルリポジトリ内で完結しそうなワークフローは動くっぽいです(ストアリリースに失敗しているメールが来て気付きました)

<img width="901" alt="スクリーンショット 2020-08-20 13 47 04" src="https://user-images.githubusercontent.com/24819529/90717959-ccd62680-e2eb-11ea-99a4-c6f0ed052707.png">
