### ISSUE TITLE
画面サイズが最初開いたウインドウのサイズに強制的に修正される。

### ISSUE THREAD

**Issue by HOkean** [KanCraft/kanColleWidget#1194]
# 画面サイズを変更(ctrlキー+マウススクロール等）でした場合に、強制的に枠のサイズに戻される。

- 期待される挙動
  -画面サイズを変更した場合は、変更を維持して欲しい
- 実際に観測される挙動
  - 画面サイズを変更した場合に、ウインドウのサイズに強制的にもどされてしまう

# 問題の再現方法

1. ゲーム画面を表示する
2. ゲーム画面の表示サイズの変更を行う（ctrlキー+マウススクロール等）
3. 強制的に最初に開いたウインドウのサイズ（ORIGINAL・SMALL等）に修正される
上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.6
- 問題が観測されなかったバージョン: 3.x.x　(バージョンは確認してませんでしたが、恐らく3.0.5ではサイズ変更可能だったと思います）
# 環境
- OS: Windows
- Chrome: 84.x.x
- 艦これウィジェット: 3.x.x

# ひとこと
いつもありがとうございます。
私の使い方が特殊な性もありますが（オリジナルの80%サイズで使用）
画面のサイズが変更できずに困っております。
できましたら、改善をお願いいたします。

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by otiai10** [comment]
@HOkean @wifeofvillon 
整理ありがとうございます。たぶんここと同じ要件になったと思うんですが、ここ閉めてもいいですか？こっちで話しましょう。
https://github.com/KanCraft/kanColleWidget/issues/1136

**Comment by HOkean** [comment]
ありがとうございます。
こちらで閉めさせていただきます。
