### ISSUE TITLE
編成キャプチャ画面でのキャプチャ範囲変更方法

### ISSUE THREAD

**Issue by YH843** [KanCraft/kanColleWidget#1198]
# 問題の概要
編成キャプチャでのキャプチャ範囲の変更ができません。
また、行、列、ページの数値を変更することもできません。
- 期待される挙動
  - 編成キャプチャでのキャプチャ範囲の変更が可能
  - 行、列、ページの数値変更が可能。

# 問題の再現方法
1. Google Chromeで艦これウィジェットの編成キャプチャ画面を開く。
2. キャプチャ範囲の変更や行、列、ページの数値変更（スピンボタンや直接入力）ができない。

再現性 100%。

# 問題が起きているバージョン

- 問題が観測されるバージョン: ver 3.0.6

# 環境

- OS: Windows　10Home
- Chrome: 84.0.4147.135（Official Build） （64 ビット）
- 艦これウィジェット: 3.0.6

# ひとこと

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

艦これウィジェットの使い方も読んだのですがそもそもキャプチャ範囲の変更が可能かどうか？などがわかりませんでしたのでissueとして起票をさせてください。
https://github.com/KanCraft/kanColleWidget/wiki/%E8%89%A6%E3%81%93%E3%82%8C%E3%82%A6%E3%82%A3%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9

**Comment by misogena** [comment]
V3への更新にまずはお礼申し上げます。
イベントを契機に艦これ復帰して同じ問題につきあたりました。
Chromeのバージョン：バージョン: 85.0.4183.83（Official Build） （64 ビット）

V2の頃は
・行と列の数字が変更できた
・画面のX座標とY座標どの地点から画面の何％分を撮影するか指定できた

の二点があったと記憶していますが、現状の編成キャプチャだと
・行と列の数字を変更しようとしても反応しない
・撮影範囲の指定メニューがなくなっている

となっています。（後者についてはレイアウトの変更で見落としているかもしれません）。
二点のうち前者については、6人未満の編成や直近のドロップ一覧を複数ページまとめる場合等に重宝していました。

**Comment by otiai10** [comment]
ご指摘ありがとうございます。TODOが残ってました。

https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Components/DeckCapture/SideBar.tsx#L35-L48
