### ISSUE TITLE
機能拡張アイコンバーの表示

### ISSUE THREAD

**Issue by sera927** [KanCraft/kanColleWidget#1200]
# 問題の概要
- 期待される挙動
  - 拡張機能のアイコンバーを表示することができ、そこから青葉のカメラを起動できる
- 実際に観測される挙動
  - 拡張機能のアイコンバーを表示させる方法が無い？

# 問題が起きているバージョン
- 問題が観測されるバージョン: 3.0.6

# 環境
- OS: MacOS 10.15.4
- Chrome: 85.0.4183.83
- 艦これウィジェット: 3.0.6

# ひとこと
Ver.3系の一般公開ありがとうございます。便利に使わせてもらっています。

スクリーンショット機能については、現状、青葉のカメラの方が私に向いているため、
艦これウィジェットを使っている時でも青葉のカメラが使えるようになれば嬉しいなと
思いました。
(ただ、ゲーム用のウィンドウには余計な物を表示させないという艦これウィジェットの
 思想からは外れてしまうとも考えられますので、却下でも構いません。)

**Comment by otiai10** [comment]
そうですね、青葉のカメラというの作ってる人なら対応できるんではないかと思います。

**Comment by otiai10** [comment]
青葉のカメラをつくっている人の降臨を待っていましたが降臨しないので閉じます。すみません
