### ISSUE TITLE
ウィジェット起動後、しばらくすると勝手にミュートになる

### ISSUE THREAD

**Issue by adm124** [KanCraft/kanColleWidget#1201]
ウィジェット起動後、しばらくすると勝手にミュートになる

- 期待される挙動
  - 起動後、こちらが操作しない限りミュートに移行しないよう改善してほしい。
- 実際に観測される挙動
  - ミュートになるタイミングはランダム。起動毎一度だけ発生する。
  - 勝手にミュートに移行した際のミュートアイコンはミュートではない状態を示したままになっている。

# 問題の再現方法

不明。ランダムなタイミングで気が付くとミュートに移行している。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.6

# 環境

- OS: Windows10
- Chrome: 84.0.4147.135
- 艦これウィジェット: 3.0.6

# ひとこと

ミュートボタンを操作することで正常に戻るので重要度の高い問題ではないかと思いますが確認して頂けると幸いです。

**Comment by otiai10** [comment]
#1170 と同じ問題ではないですか？

**Comment by otiai10** [comment]
返事が無いのとたぶん #1170 と似てるのでここはcloseします
