### ISSUE TITLE
タイマーの残り時間バッジ表示機能の再実装

### ISSUE THREAD

**Issue by adm124** [KanCraft/kanColleWidget#1202]
以前のバージョンにあった、ウィジェットアイコンに遠征などタイマーの残り時間をバッジ表示する機能を再実装してほしいです。

**Comment by otiai10** [comment]
@adm124 どういう仕様でしたっけ？

**Comment by ta-yamaoka** [comment]
@adm124 さんが言っているのは、恐らくこの画像のようなものだと思います。
詳細仕様はわかりませんが、直近遠征の残り時間が表示されているものだと思います。
![image](https://user-images.githubusercontent.com/11879583/92389885-dd442900-f154-11ea-8392-ab332070131c.png)
