### ISSUE TITLE
ポップアップにコントロールを奪われることについて。／常時最前面表示機能について。

### ISSUE THREAD

**Issue by humohumosanae** [KanCraft/kanColleWidget#1204]
-他のウィンドウモードのゲームが起動している間、通知のポップアップが前面に出て操作が奪われるのを防止できないでしょうか？FPS系ゲーム中に急にコントロールを奪われると困るので・・・。理想は通知があった音だけだしてポップアップは前面にはでないようにな感じで・・・。

もう一つ。

艦これウィジェットの画面を常に最前面に表示する機能をつけることは可能でしょうか？例えば設定項目に「常に最前面に表示」のチェックを作るとか・・・。

- OS: Windows10 Home 18363.1016
- Chrome: 85.0.4183.83
- 艦これウィジェット: ver 3.0.6

**Comment by wifeofvillon** [comment]
@humohumosanae 

最前面表示については #1021 で「やりたい気持ちはあるが(Chrome拡張の範囲では)難しい」という結論になっていますね

通知設定で音を設定→通知をオフにすると音だけにできるようですが、そちらはどうですか？

**Comment by humohumosanae** [comment]
> @humohumosanae
> 
> 最前表示については[＃1021](https://github.com/KanCraft/kanColleWidget/issues/1021)で「やりたい気持ちはあるが（Chrome拡張の範囲では）難しい」という結論になっていますね

なるほど、意外に難しいものなんですね最前面表示・・・。

> 
> 通知設定で音を設定→通知をオフにすると音だけにできるようですが、そちらはどうですか？

通知をオフにして音を設定したら音だけでお知らせしてくれました。欲を言えば通知欄には残ってほしかったですが一先ずコントロール奪われることはなくなりました。ありがとうございます。

**Comment by xia-sava** [comment]
@humohumosanae 
Windows でウィンドウ最前面固定はそれ用のアプリを別に使うのが良いと思います．
自分の環境では「かざぐるマウス」というのを使っていましたが，これは今調べたら discon のようで……

ちょい検索したら [最前面でポーズ](https://www.vector.co.jp/soft/dl/winnt/util/se468861.html) というアプリがあるようです．「Windows 最前面固定」で検索してみるといいかもです．

**Comment by otiai10** [comment]
これ閉じていいですか？

**Comment by otiai10** [comment]
返事が無いので閉じます
