### ISSUE TITLE
Wikiの更新通知時、コミットメッセージを一緒にツイートする

### ISSUE THREAD

**Issue by wifeofvillon** [KanCraft/kanColleWidget#1205]
# 提案の概要

related #1184

現在どのファイルが更新されたかだけツイートしているのでどこが変わったのかツイートだけではわからない。

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">Wikiが更新されました！ありがとう！！<br><br>&gt; FAQ<br>wifeofvillonさん より<a href="https://twitter.com/hashtag/%E8%89%A6%E3%81%93%E3%82%8C%E3%82%A6%E3%82%A3%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88?src=hash&amp;ref_src=twsrc%5Etfw">#艦これウィジェット</a><a href="https://t.co/neinyoFgxX">https://t.co/neinyoFgxX</a></p>&mdash; 艦これウィジェットちゃん (@KanColleWidget) <a href="https://twitter.com/KanColleWidget/status/1297734111000502272?ref_src=twsrc%5Etfw">August 24, 2020</a></blockquote>

以下のようにコミットメッセージを含めることで、変更箇所を明示できないか

```
更新されました！ありがとう！

> FAQ - 艦これウィジェットちゃんが自動化したことについて
wifeofvillonさん より
```

**Comment by wifeofvillon** [comment]
`gollum`のpayloadにコミットメッセージが含まれないんですね… 難しいな

[Webhook events and payloads - GitHub Docs](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#gollum)

**Comment by otiai10** [comment]
Twitter API 連携系の機能はいったんすべてclose
