### ISSUE TITLE
艦これウィジェットのツイッターするやつです

### ISSUE THREAD

**Issue by KOTOPI** [KanCraft/kanColleWidget#1207]
質問です。ウィジェットでツイッターできなくなったので
「艦これウィジェットのツイッターするやつです」というアプリ解除しちゃってもいいですか？
再実装予定がもしあるなら解除せずに置いておきますが

**Comment by otiai10** [comment]
削除しちゃっていいです。どうせTwitter連携を再実装した段階で改めて追加することができるので。
