### ISSUE TITLE
編成キャプチャカスタム構成を保存すると削除できない

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1211]
# 問題の概要

保存した編成キャプチャカスタム構成を削除することができない．削除機能がほしいです．

![SS_20200907_221800](https://user-images.githubusercontent.com/679532/92391748-29dd3380-f158-11ea-883b-11b79de06853.jpg)

テストで構成をテキトーに保存してたらひどいことにｗ

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.9

**Comment by otiai10** [comment]
これは設定画面で削除できるっす

**Comment by xia-sava** [comment]
あっホントだ見落としてました！

この設定画面の「編成キャプチャ設定」セクション自体を切り出して，
キャプチャ画面から直接呼び出せるようなボタンがあると，
機能が感覚的に理解しやすくて良くなりそうですね．
