### ISSUE TITLE
支援艦隊の遠征を出した際には通知を行わないようにしたい

### ISSUE THREAD

**Issue by moriyadetteiu** [KanCraft/kanColleWidget#1221]
# 問題の概要

- 期待される挙動
  - 支援艦隊（前衛支援任務(南方)など）の遠征に出した際に通知されない
- 実際に観測される挙動
  - 支援艦隊（前衛支援任務(南方)など）の遠征に出した際に通知される

# 問題の再現方法

1. 支援艦隊（前衛支援任務(南方)など）に遠征を出す
2. 支援艦隊の遠征の通知が登録される

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.13

# 環境

- OS: Windows
- Chrome: 85.0.4183.121
- 艦これウィジェット: 3.0.13

# ひとこと
実際には支援艦隊の遠征の場合にも通知が必要な人も存在すると思うので、設定画面に `通知オフ遠征ID` のような項目を追加し、任意で編集可能な形をとるのがいいと思います。この形であればイベントの支援艦隊も随時ユーザ側で設定可能ですし。  
上記機能が必要な理由は、 `支援艦隊を出す → 該当出撃終了 → 通常遠征を出す → 艦これを終了` とし、別のことを始めた際に支援艦隊の完了通知が来た際に（必要のない）遠征の更新をしようと艦これを開く、といったことが発生していたためです。

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by moriyadetteiu** [comment]
上記の実装方針で問題ないようであれば、forkして自前で実装、PRを出す形にしたいのですが、如何でしょうか。

**Comment by otiai10** [comment]
ありがとうございます。大枠同意なんですが、1点確認です。
問題は、以下Aと以下Bのどちらですか？

# A

1. 第２艦隊を支援遠征に出す
2. 第１艦隊で出撃する
3. 出撃が終了し、第２艦隊が自動的に遠征から戻る
4. 第２艦隊の支援遠征終了通知が鳴る **（← 問題）**

# B

1. 第２艦隊を支援遠征に出す
2. 第１艦隊で出撃する
3. 出撃が終了し、第２艦隊が自動的に遠征から戻る
4. 第２艦隊を通常の遠征に出す
5. 第２艦隊の支援遠征終了通知が鳴る **（← 問題）**
6. 第２艦隊の通常遠征終了通知が鳴る

**Comment by moriyadetteiu** [comment]
ご確認ありがとうございます。

AとBどちらのパターンも当てはまるかと思います。
支援遠征の通知自体が不要という認識です。

**Comment by moriyadetteiu** [comment]
・補足
ソースのほうざっと目を通しましたが、
https://github.com/KanCraft/kanColleWidget/blob/3177df95132cb87d23f978debaa70f7161fe236b/src/js/Applications/Background/Controllers/Request/Mission.ts#L6-L14
ここの部分で設定を見に行って通知オフなIDだった場合はif文などを挟んで通知を蹴らない、もしくは `NotificationSetting.enabled = false` を挟むような形のイメージですね。

**Comment by otiai10** [comment]
ありがとうございます！
遠征IDがユーザにとって自明か、とか、そもそもカタログデータをどう管理するか、という関心があるので具体的な設定画面のUXをどうするか僕の方ではアイデアはありませんが、ご指摘いただいた問題はそのとおりだと思うので、ぜひPRいただければと思います。

勉強させていただきます！
