### ISSUE TITLE
遠征IDの追加: 142

### ISSUE THREAD

**Issue by toko-m** [KanCraft/kanColleWidget#1222]
遠征ID 142 確認ください
2020/9に実装された、南方海域「E2: 強行鼠輸送作戦」に未対応のようです。

- https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81
- https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Models/Queue/missions.ts

**Comment by wifeofvillon** [comment]
先月(2020/09)追加された遠征は2種類 ちなみに「南西海域戦闘哨戒」を今から実行できたりしますか？私は次のリセットまで確認できないので

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">08▼【新遠征】の実装<br>南方海域、南西海域にそれぞれ一種、計二種の【新遠征】を実装します。<br>●南方海域：新遠征【強行鼠輸送作戦】<br>●南西海域：新遠征【南西海域戦闘哨戒】<br>※最大一回/月 遠征実施可能<br>※交戦II型遠征<br>※遠征への出発には、それぞれ前提となる遠征群の成功が必要です。<a href="https://twitter.com/hashtag/%E8%89%A6%E3%81%93%E3%82%8C?src=hash&amp;ref_src=twsrc%5Etfw">#艦これ</a></p>&mdash; 「艦これ」開発/運営 (@KanColle_STAFF) <a href="https://twitter.com/KanColle_STAFF/status/1306551903933718529?ref_src=twsrc%5Etfw">September 17, 2020</a></blockquote>

[【艦これ】定期任務 > missions - Google スプレッドシート](https://docs.google.com/spreadsheets/d/1F6gDmwzrKU6-QGqvA3Le1Jes7al7TtO8BR5RSrharvY/edit#gid=382951184)

**Comment by xia-sava** [comment]
「南西海域戦闘哨戒」自分は既に終えてしまっていますが，出す時にコンソールで（画面の表記と同一の）ID 46 なのを確認しています．

**Comment by otiai10** [comment]
@各位 ありがとうございます！！
