### ISSUE TITLE
大破進軍防止窓の誤クリック防止タイマーをもう少し短く

### ISSUE THREAD

**Issue by mtl774** [KanCraft/kanColleWidget#1223]
大破進軍防止窓の誤クリック防止タイマーが8000msに変更されたようですがまだ長いようです。
「次」が出る瞬間を狙って１クリックすると、ゲームは進行するがキャプチャされない事象が起こります。
もともと１クリック勢なので、体内時計で覚えてる感覚です。
なので、もう少し短く、7900～7800msにできないでしょうか。

「次」を目視確認してクリックすれば上記事象は起こりません。

# 問題の再現方法

１．戦闘終了する
２．「次」が出る瞬間を狙って１クリックする（難しい
３．戦闘結果画面で窓が出ない
４．2回目の「次」でクリックする
５．「新たな仲間が……」の文字被りのスクショで窓が表示される

上記の方法により、１０％以下の確率で、再現する。（確率は個人差あると思います）

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.0.13
- 問題が観測されなかったバージョン: 3.0.6

# 環境

- OS: Windows10
- Chrome:85.0.4183.121
- 艦これウィジェット: 3.0.13

# ひとこと

**Comment by otiai10** [comment]
ありがとうございます。変更するのが妥当だと思います。

CC https://github.com/KanCraft/kanColleWidget/issues/1213, https://github.com/KanCraft/kanColleWidget/pull/1215
@xia-sava

**Comment by xia-sava** [comment]
こちらの環境でも 8000ms にした以降も少しだけ当該現象が発生していて，もう気持ち短めの方が良いのかなーと思っていたところでした．

特に厳密な計測とかせずにひとまず 7800ms にした PR を作りました．
