### ISSUE TITLE
6-5海域マス数表示のミス

### ISSUE THREAD

**Issue by AK-AKAK-AK** [KanCraft/kanColleWidget#1232]
# 問題の概要

6-5海域で防止窓の海域情報の表示の戦闘数が1多い。
1戦目で6-5(2)、4戦目では6-5(5)と表示される。

現状6-5で防止窓を出した状態で再現性100%

# 問題が起きているバージョン

V3全て

# 環境

- OS: Windows
- Chrome: 85.0.4183.121
- 艦これウィジェット: 3.0.14

**Comment by otiai10** [comment]
6-5、開放されていなかった

**Comment by xia-sava** [comment]
来週くらいに今月の 6-5 やろうと思ってるので，リクエストログ取ってみますね．

（個人的には，これ表示だけで実害がほとんどないので修正されなくても特に困りません）

**Comment by xia-sava** [comment]
出撃から帰還までのログを取りました．API だけ抽出．

```
"http://203.104.209.150/kcsapi/api_req_map/start"
(基地航空隊をセット)
"http://203.104.209.150/kcsapi/api_req_map/start_air_base"
"http://203.104.209.150/kcsapi/api_req_sortie/battle"
"http://203.104.209.150/kcsapi/api_req_sortie/battleresult"
"http://203.104.209.150/kcsapi/api_get_member/ship_deck"
"http://203.104.209.150/kcsapi/api_req_map/next"
（1戦目を終えて羅針盤，この時点で 6-5(2) 表示）
"http://203.104.209.150/kcsapi/api_req_sortie/battle"
"http://203.104.209.150/kcsapi/api_req_sortie/battleresult"
"http://203.104.209.150/kcsapi/api_get_member/ship_deck"
"http://203.104.209.150/kcsapi/api_req_map/next"
（2戦目を終えて羅針盤，この時点で 6-5(3) 表示）
"http://203.104.209.150/kcsapi/api_req_sortie/battle"
"http://203.104.209.150/kcsapi/api_req_sortie/battleresult"
"http://203.104.209.150/kcsapi/api_get_member/ship_deck"
"http://203.104.209.150/kcsapi/api_req_map/next"
（3戦目を終えて羅針盤，この時点で 6-5(4) 表示）
"http://203.104.209.150/kcsapi/api_req_battle_midnight/sp_midnight" （開幕夜戦）
"http://203.104.209.150/kcsapi/api_req_sortie/battleresult"
"http://203.104.209.150/kcsapi/api_get_member/ship_deck"
"http://203.104.209.150/kcsapi/api_req_map/next"
（4戦目を終えて羅針盤，この時点で 6-5(5) 表示）
"http://203.104.209.150/kcsapi/api_req_combined_battle/ec_battle" （自通常艦隊 vs 敵連合艦隊）
"http://203.104.209.150/kcsapi/api_req_combined_battle/ec_midnight_battle" （夜戦もやった）
"http://203.104.209.150/kcsapi/api_req_combined_battle/battleresult"
（帰還）
"http://203.104.209.150/kcsapi/api_port/port"
```

**Comment by otiai10** [comment]
> （1戦目を終えて羅針盤，この時点で 6-5(2) 表示）

ここがそもそも間違ってる、ってことですか？

**Comment by otiai10** [comment]
なるほど、

`api_req_map/start_air_base` が `OnAirBattleStarted` を、`api_req_sortie/battle` が `OnBattleStarted` をトリガしており、それぞれ中で `Sortie.context().battle();` を呼んでいますね。

https://github.com/KanCraft/kanColleWidget/blob/7e0d874c056b28dd2e8e185067f35634dff4ca7f/src/js/Applications/Background/Controllers/Request/Battle.ts#L49-L65

6-5なら回避みたいなやり方もできるが、正しくは `api_req_map/next` が呼ばれたらflushみたいな設計だろうな。さすがに`api_req_map/next`を呼ばない次戦扱いの戦闘開始は無いと思いたい。

**Comment by xia-sava** [comment]
> ここがそもそも間違ってる、ってことですか？

そうですね，このタイミングでは1戦目を終えたところなので `(1)` と表示されるべき，ということだと思います．

個人的な妄想なんですが，ダッシュボードの疲労回復タイマーの辺りに「現在戦闘中の海域番号」が表示されてほしいなと思っているので，戦闘開始のタイミングくらいで context が決定される感じだと嬉しみが増しそうです．

**Comment by xia-sava** [comment]
3.2.10 で 6-5 やってますが，表記の挙動が以下のようになっています．

<table>
<tr>
    <th>状況
	<th>3.2.9以前
	<th>3.2.10
	<th>期待される挙動
<tr>
    <th>1戦目終了後
	<td>"6-5(2)"
	<td>"6-5"
	<td>"6-5(1)"
<tr>
    <th>2戦目終了後
	<td>"6-5(3)"
	<td>"6-5(1)"
	<td>"6-5(2)"
</table>

APIリクエストとユーザ操作は以前から特に変更なしの模様です．

<table>
<tr>
    <th>ユーザ操作
    <th>APIリクエスト
<tr>
    <td>海域選択画面で 6-5 を選択
    <td>/kcsapi/api_req_map/start
<tr>
    <td>基地航空隊をセット
    <td>/kcsapi/api_req_map/start_air_base
<tr>
    <td>1戦目 陣形選択
    <td>/kcsapi/api_req_sortie/battle
<tr>
    <td>夜戦 "追撃せず" を選択
    <td>/kcsapi/api_req_sortie/battleresult
<tr>
    <td>戦果表示 "次" クリックで大破進撃窓に "6-5" 表示
    <td>-
<tr>
    <td>進撃
    <td>/kcsapi/api_get_member/ship_deck<br>
        /kcsapi/api_req_map/next
<tr>
    <td>羅針盤
    <td>-
<tr>
    <td>2戦目 陣形選択
    <td>/kcsapi/api_req_sortie/battle
<tr>
    <td>夜戦 "追撃せず" を選択
    <td>/kcsapi/api_req_sortie/battleresult
<tr>
    <td>戦果表示 "次" クリックで大破進撃窓に "6-5(1)" 表示
    <td>-
<tr>
    <td>進撃
    <td>/kcsapi/api_get_member/ship_deck<br>
        /kcsapi/api_req_map/next
</table>

**Comment by otiai10** [comment]
ぐぬぬ…直します！

**Comment by xia-sava** [comment]
3.2.11 ですが，6-5 は正常に1戦目に `6-5 (1)` 2戦目に `6-5 (2)` と表示されますが，
他の海域で例えば 1-5 だと1戦目に `1-5` 2戦目に `1-5 (2)` と表示されますね．

これはもしかしたら 3.2.10 からそうだったかもしれません，すいませんここ数日デイリー巡回しかやってなくて他海域での表示を見てなかった……

https://github.com/KanCraft/kanColleWidget/blob/501098c37dc4ec6db383f90b0d2a610564e4fd0e/src/js/Applications/Models/Sortie/index.ts#L38

ここが `depth: 1` からスタートならいけるように見える……時間が取れたらこちらでもビルドして試してみます．

**Comment by xia-sava** [comment]
> ここが depth: 1 からスタートならいけるように見える

やってみたらひとまず 1-1 と 6-5 で問題なさそうに見えたので雑にプルリク投げます．
