### ISSUE TITLE
ウィンドウサイズ拡大後スクリーンショットを撮ると正しく撮影されない

### ISSUE THREAD

**Issue by azu-iti** [KanCraft/kanColleWidget#1275]
# 問題の概要
Originalで起動後、フルスクリーン（1920*1200）にし、その状態でスクリーンショットを撮影すると、画面の内容が部分的にしか撮影されない

- 期待される挙動
  - 画面内容のスクリーンショット画像が作成される
  - 
- 実際に観測される挙動
  - 画面内容が一部だけ反映され、他は白い画像が作成される

# 問題の再現方法

1. Originalで艦これウィジェットを起動する
2. フルスクリーンにする
3. カメラアイコンでスクリーンショットを撮影する

2回撮影して2回なりました。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.2.14

# 環境

- OS: Windows
- Chrome: : 87.0.4280.88（Official Build） （64 ビット）
- 艦これウィジェット: 3.2.14

# ひとこと
キャプチャ用のバッファのサイズがウィンドウサイズの変更に追従してないのでは？

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by otiai10** [comment]
ありがとうございます。もしOS特有の話であった場合、pull-reqお待ちしてます

**Comment by otiai10** [comment]
@azu-iti この現象はまだ起きてますか？

**Comment by azu-iti** [comment]
@otiai10 
3.2.47にて現象が発生しない事を確認しました。
修正ありがとう！
