### ISSUE TITLE
修復開始通知の表示不能

### ISSUE THREAD

**Issue by KFC03724** [KanCraft/kanColleWidget#1279]
# 問題の概要
入渠開始した時に表示されるWindowsの通知表示の内容が上手く表示されない場合がある

- 期待される挙動
  - Windowsの通知に正しい修復予定時刻が表示される
- 実際に観測される挙動
  - 「修復予定時刻はNaN:NaNです。」と表示される

# 問題の再現方法

1. 損傷を受けた艦娘を入渠させる（素早く2人目の艦娘を入渠させると再現できるかもしれません）
2. Windows10の通知が表示される
3. 「修復予定時刻はNaN:NaNです。」と表示される
![20210101_091325](https://user-images.githubusercontent.com/18262341/103475029-0025d780-4ded-11eb-87f9-47f287007519.jpg)

上記の方法により、100％（？）の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.2.14
- 問題が観測されなかったバージョン: 3.x.x（不明）

# 環境

- OS: Windows10 Pro 64bit
- Chrome: 87.0.4280.88
- 艦これウィジェット: 3.2.14

# ひとこと
ご無沙汰しております。やん・じしゅかです。本年も宜しくお願いいたします。
今後はこちらへ投稿すればよろしいのでしょうか？

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by otiai10** [comment]
ありがとうございます。これは100%ですか？
> 100％（？）の確率

と書いてありますが

**Comment by KFC03724** [comment]
一度事象が発生して以降、継続してこの様に表示されております。
その間、ブラウザを閉じたりPCを再起動したり等は行っておりませんが。

**Comment by otiai10** [comment]
とりあえずサーバは落ちていないので、Chrome拡張側をリスタート（つまりブラウザをいったん完全終了）してみてください

サーバのヘルスチェック： https://api-kcwidget.herokuapp.com/

**Comment by otiai10** [comment]
> 今後はこちらへ投稿すればよろしいのでしょうか？

そのほうがうれしいです！！

**Comment by KFC03724** [comment]
> とりあえずサーバは落ちていないので、Chrome拡張側をリスタート（つまりブラウザをいったん完全終了）してみてください
> 
> サーバのヘルスチェック： https://api-kcwidget.herokuapp.com/

Chromeを終了させ、タスクマネージャーの[詳細]でchrome.exeが一切稼働していない事を確認の上、Chromeを再度起動し艦これをスタートさせ損傷を受けた艦娘一名を入渠させた所、今度はWindowsの通知そのものが表示されない、という事象が見られました。

艦これウィジェットの通知設定は添付ファイルの通りです。
![20210103_184441](https://user-images.githubusercontent.com/18262341/103475823-ef2c9480-4df3-11eb-916d-dc835513fa5c.jpg)

**Comment by KFC03724** [comment]
[3.2.16]にて、Chromeの履歴→閲覧データの削除→キャッシュされた画像とファイルの[データの削除]を行った所、
以下の挙動が見受けられました。
事象の発生率が100%では無い事が判りましたので、訂正させていただきます。すみません。
https://youtu.be/xjyqJuFRi9M

**Comment by otiai10** [comment]
ありがとうございます。右上のアイコンから作られた別窓は使ってないということですか？

艦これウィジェットの部分画像取得は、基本的に別窓が作られた状態を基準にして座標計算していますゆえ、別窓使っていない場合は座標取得が定まらず、修復時間の判定ができない場合が多いです。

**Comment by KFC03724** [comment]
> ありがとうございます。右上のアイコンから作られた別窓は使ってないということですか？
> 
> 艦これウィジェットの部分画像取得は、基本的に別窓が作られた状態を基準にして座標計算していますゆえ、別窓使っていない場合は座標取得が定まらず、修復時間の判定ができない場合が多いです。

ご返信有り難うございます。
＞右上のアイコンから作られた別窓
すみません、この機能は存じませんでした。
これはダッシュボード機能の事でしょうか。であれば時々見る程度で今回の録画時には使用しておりませんでした。

**Comment by otiai10** [comment]
ゲームのタブをいったん閉じて、右上アイコンから錨マークをクリックしてみてください。

**Comment by KFC03724** [comment]
> ゲームのタブをいったん閉じて、右上アイコンから錨マークをクリックしてみてください。

ご助言有り難うございます！
恥ずかしながら、[抜錨！]ボタンについて無知でした。ようやくこのボタンの意味と使い方を理解できました。
[抜錨！]ボタン押下しての別ウインドウでの条件下にて、修復終了時刻通知の正常動作を確認できました。
よろしければ、以下の動画のご確認をお願いいたします。
https://youtu.be/r1Z_CXoWbEQ

以降は、[抜錨！]ボタンを使用して艦これウィジェットを使用させていただきます。

**Comment by otiai10** [comment]
右上アイコンからサイズ選択も試してみてください。便利なはずです。

詳しくはこちら https://github.com/KanCraft/kanColleWidget/wiki/%E8%89%A6%E3%81%93%E3%82%8C%E3%82%A6%E3%82%A3%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9

このissueはcloseでいいですか？

**Comment by KFC03724** [comment]
＞右上アイコンからサイズ選択
はい、既に試しております。便利な機能を有り難うございます。
本件はcloseでお願いいたします。
