### ISSUE TITLE
dependabotのPRにともなうテストリリースが多すぎやしないか？

### ISSUE THREAD

**Issue by otiai10** [KanCraft/kanColleWidget#1319]
1. dependabotによるcontributionはテストリリース判定に使わない
2. dependabotによるcontributionはリリースノートに含めない

両方やらないとダメ

**Comment by otiai10** [comment]
テストリリース判定には含めて、リリースノートには含めて、設定画面の表示には含めないのが１番良いかな

**Comment by otiai10** [comment]
リグレッションの評価のために、テストリリースは必要なんだけど、それをTwitterでアナウンスする必要は無い、って感じな気がする

**Comment by xia-sava** [comment]
ライブラリのアップデートは黙ってテスト版（青帯）に流してしまって，それ以外のものがあった時のみ +1 を募って集まったら本番リリース，ということですよね．それが妥当だと思います．

**Comment by otiai10** [comment]
完全に今developブランチでバグってる模様。土日で直します。
