### ISSUE TITLE
遠征IDの追加: 115

### ISSUE THREAD

**Issue by xia-sava** [KanCraft/kanColleWidget#1353]
遠征ID 115 確認ください

- https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81
- https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Models/Queue/missions.ts

B6 「南西諸島捜索撃滅戦」 マンスリー遠征

**Comment by otiai10** [comment]
B6、とかあるんすね。API上は115だが、WikiではB6、ってことですかね

**Comment by otiai10** [comment]
#1482 で115は追加されたもよう
