### ISSUE TITLE
遠征IDの追加: 115

### ISSUE THREAD

**Issue by chocolat-shop** [KanCraft/kanColleWidget#1482]
遠征ID 115 確認ください

wiki上のID・遠征名は
ID:B6
遠征名： 精鋭水雷戦隊夜襲(マンスリー・交戦II型)
遠征時間：05:50:00
弾薬消費：95%
燃料消費：95%
報酬：110EXP、燃料×600、弾薬×1000、鋼材×600、ボーキサイト×600、開発資材×0～5、改修資材×0～1

全6隻。軽(旗艦固定)1隻、駆5隻必要。／「軽×1,駆×5」
艦隊の合計値で、火力410 / 対空390 / 対潜410 / 索敵340 以上

となっています。

- https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81
- https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Models/Queue/missions.ts

**Comment by wifeofvillon** [comment]
```
  "115": { // マンスリー遠征
    "title": "精鋭水雷戦隊夜襲",
    "time": 21000000
  },
```

値だけ置いておきます 挿入先は[ここ](https://github.com/KanCraft/kanColleWidget/blob/e83b9e67fb13d2924f8a0560e20ec09c4558b404/src/js/Applications/Models/Queue/missions.ts#L238)
(ローカル環境の作り直しからやるのでどなたか巻き取っていただけると助かります 🙏 )

FYI: [定期任務/遠征ID一覧](https://docs.google.com/spreadsheets/d/1F6gDmwzrKU6-QGqvA3Le1Jes7al7TtO8BR5RSrharvY/edit#gid=382951184&range=A32:L32)

**Comment by otiai10** [comment]
3.2.55で追加されていると思うのでcloseします
