### ISSUE TITLE
スクショのショートカット機能を無効化できるようにしてほしい

### ISSUE THREAD

**Issue by SUGI017** [KanCraft/kanColleWidget#1490]
# 問題の概要

- 期待される挙動
  - 設定でショートカット機能の無効化ができ、ctrl+shift+0を押してもスクショを撮らないようにしたい
- 実際に観測される挙動
  - 設定にショートカット機能の無効化の項目がない

# 問題の再現方法

1. 別アプリケーションがアクティブのとき、ctrl+shift+0を押下する
2. 艦これウィジェットでスクリーンショットが撮影されてしまう
3. ctrl+shift+0を他のアプリケーションで使用しづらい事が観測される

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.2.55
- 問題が観測されなかったバージョン: 3.x.x

# 環境

- OS: Windows 10 Home
- Chrome: 91.0.4472.124（Official Build） （64 ビット）
- 艦これウィジェット: 3.2.55

# ひとこと

（設定項目を見落としていたら申し訳ございません）

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by xia-sava** [comment]
拡張機能側ではなく Chrome 本体側の設定でショートカットキーを変更したり無効化したりできますよー
参考資料 → https://www.atmarkit.co.jp/ait/articles/2004/01/news020.html

**Comment by SUGI017** [comment]
ありがとうございます！初歩的で申し訳ないです……
