### ISSUE TITLE
出撃から帰投後、母港画面に大破進撃防止窓が黒い状態で残る

### ISSUE THREAD

**Issue by KFC03724** [KanCraft/kanColleWidget#1517]
お世話になっております。
以下挙動を確認致しましたので報告させていただきます。

# 問題の概要
現在【夏イベ】E3 戦力ゲージ(一本目) を攻略中ですが、出撃から帰投後に大破進撃防止窓が黒い状態で画面に残ります。
- 期待される挙動
  - 出撃から帰投後に大破進撃防止窓が消去される。
- 実際に観測される挙動
  - 大破進撃防止窓が黒い状態で画面に残る。

# 問題の再現方法

1. E3 戦力ゲージ(一本目)に出撃する
2. 戦闘を終え母港に帰投する
3. 母港画面に自動で遷移する
4. 母港画面左上の大破進撃防止窓が黒い状態で画面に残る事象が観測される

上記の方法により、？％の確率で、再現する。
※事象が再現されたりされなかったりの模様です。

# 問題が起きているバージョン
3.2.56（テストリリースバージョン）
- 問題が観測されるバージョン: 3.2.56
- 問題が観測されなかったバージョン: すみません試しておりません。

# 環境

- OS: Windows10  Home 21H1
- Chrome: 93.0.4577.63 (Official Build) (64 ビット)
- 艦これウィジェット: 3.2.56（テストリリースバージョン）

# ひとこと
最初KinzaというChrome互換ブラウザにて利用させていただき事象を確認し、Chromeでやり直して「あ、出ない」と思っておりましたらもう一度出撃して母港に帰投しましたら事象が発生しました。
尚、艦これウィジェットの起動は[MEMORY]モードにて行いました。

このリンクをみました 👉 [使いはじめる前に](![スクリーンショット_20210913_1422](https://user-images.githubusercontent.com/18262341/133028362-95f0e1fe-4717-4745-a512-88aa76a62b14.png))
![スクリーンショット_20210913_1422](https://user-images.githubusercontent.com/18262341/133028542-cfd7e9d8-57c0-493c-9163-25b00e47ca39.jpg)

**Comment by otiai10** [comment]
2024年のv4にて対応するため、一度closeさせてください
