### ISSUE TITLE
コメントではなくReviewベースのリリースコントロール

### ISSUE THREAD

**Issue by otiai10** [KanCraft/kanColleWidget#1541]
# 現状

* コメントで 👍 と言ってもらうとリリースできる

# 問題

* 誰に 👍 と言ってほしいか不明瞭（指名してないので当たり前ではあるんだが）
* 同様コメントがfoldされる仕様により、誰が 👍 と言ってくれているか見えにくい

# 解決案

* RELEASE PullRequestには、Reviewerを定義し、reviewerをアサインする
* N人中n人のapprovalがあればリリースする
* テスターグループは基本的に解散。アクセスコントロールのためのChromeアプリは将来的に別立ても検討。

#1446

**Comment by KFC03724** [comment]
👍

**Comment by otiai10** [comment]
2024年のv4にて対応するため、一度closeさせてください

Twitter API 利用制限により、民主的リリースプロセスの実現はむずかしくなった印象
