### ISSUE TITLE
大破進撃防止窓にマウスオーバーすると大破進撃防止窓が消失する（軽微）

### ISSUE THREAD

**Issue by KFC03724** [KanCraft/kanColleWidget#1648]
# 問題の概要
大破進撃防止窓にマウスオーバーすると大破進撃防止窓が消失する。
但し、再度マウスオーバーすると再表示され、マウスオーバーの都度消失と再表示を繰り返す。

- 期待される挙動
  - マウスオーバーをしてもしなくても大破進撃防止窓が常に表示され続ける
- 実際に観測される挙動
  - マウスオーバー操作により消失と再表示が繰り返される。

# 問題の再現方法

1. 大破進撃防止窓が表示されている画面に遷移する
2. 大破進撃防止窓に対してマウスオーバーする
3. 初回マウスオーバーのとき大破進撃防止窓が消失する
4. 次回以降のマウスオーバー操作以降ではトグル的に再表示と消失が繰り返される

上記の方法により、100％の確率で、再現する。

# 問題が起きているバージョン

- 問題が観測されるバージョン: 3.2.70
- 問題が観測されなかったバージョン: 未確認です。

# 環境

- OS: Windows 10 Home
- Chrome: 102.0.5005.63（Official Build） （64 ビット）
- 艦これウィジェット: 3.2.70

# ひとこと
マウスオーバー操作をしなければいいだけの軽微な事象と考えておりますので余力がありましたらご確認とご対応の程どうぞ宜しくお願いいたします。

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by otiai10** [comment]
勝利画面をスクショ撮りたい人が、そのときは大破進撃防止を非表示にしたいかな、というのが当初思ってたことだったと思います。どう思いますか？

**Comment by roxolel** [comment]
otiaiさんのおっしゃる通りの使い方をしているので、マウスオーバー非表示→表示のままの方がありがたいです

**Comment by KFC03724** [comment]
> 勝利画面をスクショ撮りたい人が、そのときは大破進撃防止を非表示にしたいかな、というのが当初思ってたことだったと思います。どう思いますか？

その様な意図があって敢えてそうされていたのですね。知らずすみませんでした。取り下げて戴いて結構です。

**Comment by otiai10** [comment]
ご意見いただけるのはめちゃくちゃ嬉しいです！！ありがとうございます！！！！
