### ISSUE TITLE
スクショで不具合

### ISSUE THREAD

**Issue by PCEDuo** [KanCraft/kanColleWidget#1671]
# 問題の概要
[1]今回起きたもの
スクリーンショットを撮って[保存]アイコンをクリックすると
保存先選択画面が出ず、フォトアプリが起動する

[2]実はずっと起きている物
スクリーンショットの保存先指定、保存ネーム指定が
反映されない。

- 期待される挙動
[1]  スクリーンショットを撮ったあとの編集画面で[保存]をクリックすると
保存先選択画面が開く

[2]スクリーンショットを保存した時
保存設定を反映したデフォルト保保存先&指定ファイル名or
「スクリーンショット_yyyyMMdd_HHmm」の名前で指定形式で保存される。

- 実際に観測される挙動
[1]  スクリーンショットを撮ったあとの編集画面で[保存]をクリックすると
フォトアプリで画像が開く

[2]スクリーンショットを保存した時
保存設定を反映したデフォルト保保存先&指定ファイル名で保存されず
「ダウンロード_yyyyMMdd_HHmm」にってしまう(何故かファイル形式の指定は有効になってる)

# 問題の再現方法

逆に再現しない方法がわからない

上記の方法により、◯◯％の確率で、再現する。

100％

# 問題が起きているバージョン
ver 3.2.72

- 問題が観測されるバージョン: 3.x.x
- 問題が観測されなかったバージョン: 3.x.x

不明[1]の症状は今日になって現れた。
[2]に付いては2年以上の付き合い

# 環境

- OS: Windows 10 Pro 最新の状態
- Chrome: バージョン: 106.0.5249.62（Official Build） （64 ビット）
- 艦これウィジェット: 3.2.72

# ひとこと
ウイジェットの入れ直しなどでは改善しなかった。
セキュリティとか知らないうちに設定を変えてしまっている可能性も有るのだけど
正直分からない....

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by xia-sava** [comment]
[2] の方は，こちらの環境では普通に機能していますね．
「ダウンロード」という文字列がどこからともなく出てくるとは考えにくいので，設定データに古いものか何かの変な情報が残ってるとかでしょうか……

拡張機能のアイコンで右クリック→「ポップアップを検証」→アプリケーション→ローカルストレージ→ScreenshotSetting の内容を確認してみると良いかもしれません．

[1] の方はダウンロードの横のメニューでうっかり「常に開く」を設定しちゃっているとかではなかろうかー

![image](https://user-images.githubusercontent.com/679532/192787763-ffb8694e-64c1-4301-b927-a5aacaac2983.png)

**Comment by PCEDuo** [comment]
![タイトルなし](https://user-images.githubusercontent.com/6902000/192792951-6fc410d8-c647-45ae-af22-3ca263711563.jpg)
[2]の方のアイコン右クリック→[ポップアップを検証]→アプリケーションまでは見つかるんですが
ローカルゲートウェイという項目が見当たらないのですが見ている所が違うのだろうか....

[1]に付いてはダウンロード横のメニューのダウンロードがどこなのか(どの表示の部分なのか勝手に開くフォトアプリなのか
だとしたらどこからフィラくのか)分からなくて...もう少し詳しく、、申し訳ない

**Comment by xia-sava** [comment]
[2] 左側の Local Storage の▶を開くとその下にもうひとつ項目があって，そこを選ぶと真ん中に色々出てくる中に ScreenshotSetting 項目があったりなかったりします．

[1] ダウンロードが行なわれるとウィンドウの下の方にタスクバーみたいに「いまダウンロードしたファイル名」が並ぶと思います，その名前の右横に＾マークがあるのでそこをクリックです．

**Comment by PCEDuo** [comment]
[1]の方は解消したかもしれませんChromeの設定メニューにある項目で当たりならDLしたファイルを開くの部分を
削除したら正常なDL動作になりました、有難う有難う。

ちなみにファイル名はこうなってしまうのです
ウィジェットの設定では[スクリーンショット_yyyyMMdd_HHmm]
![umakuittayouna](https://user-images.githubusercontent.com/6902000/192795986-192b2a9f-1c6d-457b-81af-cfee8eb8b210.jpg)

**Comment by PCEDuo** [comment]
![setteinngu](https://user-images.githubusercontent.com/6902000/192797465-19307040-d0db-4c76-ab0e-db6915fb9c45.jpg)

[2]ですが見たらこんなんなってますね(見る場所が合ってるなら)

**Comment by xia-sava** [comment]
[1] 解決しましたか，設定画面からでも同じ設定ができると思うのでそれでたぶん大丈夫かと．おめでとうおめでとう．


[2] そこで合ってると思います，ちゃんと「スクリーンショット」になってますね……

ファイル名の「ダウンロード - 日時」の方の日時形式が ISO-8601 という形式で，艦これウィジェットで設定する yyyyMMdd_HHmm とは似てるけど全く異なるものなので，これはもう違うプログラムが違うロジックでファイル名決めちゃってそうです．

何かダウンロードファイルを自動的にどうこうするみたいな拡張が他に入ってたりしませんかね？

**Comment by PCEDuo** [comment]
[2]のどうこうするような拡張
それビンゴでした。
当面使わない拡張を全部非アクティブにしたら艦これウィジェットの
設定道理になりました、これでここ何年か喉に骨が刺さったような気分だったのが
解消されました、本当にありがとうございました。

**Comment by PCEDuo** [comment]
了解しました。
悪さをしていたのはこれですね。
![タイtwehbトルなし](https://user-images.githubusercontent.com/6902000/192909766-5f8105d7-b4c0-4b69-b16c-3f7a228c8a9a.jpg)
