### ISSUE TITLE
大破進軍窓が表示されない

### ISSUE THREAD

**Issue by spnlob** [KanCraft/kanColleWidget#1729]
# 問題の概要

大破進軍窓をゲーム内表示にしても左上に出てきません。
艦これウィジェットの別窓モードでプレイすると問題なく表示されるのですが。

- 問題が観測されるバージョン: 3.2.81

# 環境

- OS: Windows 10
- Chrome: 116.0.5845.141
- 艦これウィジェット: 3.2.81

# ひとこと

下記リンクに同様の症状があったので
「サードパーティのCookieをブロックする」→「Cookieをすべて受け入れる」に変更しましたが変化なし。
https://github.com/KanCraft/kanColleWidget/issues/1168

このリンクをみました 👉 [使いはじめる前に](https://github.com/KanCraft/kanColleWidget/wiki/%E4%BD%BF%E3%81%84%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E5%89%8D%E3%81%AB)

**Comment by spnlob** [comment]
有難うございます。

**Comment by otiai10** [comment]
サブディスプレイは使ってますか？

**Comment by spnlob** [comment]
はい。使用しています。

**Comment by otiai10** [comment]
2024年のv4にて対応するため、一度closeします
