### ISSUE TITLE
No bug, just some questions.

### ISSUE THREAD

**Issue by momocow** [KanCraft/kanColleWidget#976]
Hi, I have been a 提督 and also a user of this widget for about 4.5 years.
Thanks for a nice project. 🎉 

Oh, this is not the point of this post but a greeting from Taiwan. 😄 

-----

Now, let's get to the point.

I've read the slides you provide in the options page (and the site of the widget).
I'm wondering if it is safe (or says **legal**, for DMM or KanColle official) to load only the game frame without those (annoying 😆) advertisement iframes. (e.g. in non-default-white mode of the widget) I don't want to offense DMM or KanColle but just hope to improve the gaming experience.

I will show as below why I just said those ads to be annoying.

When loading a DMM page, it will also load approximately 162~163 iframes.
![image](https://user-images.githubusercontent.com/17778751/45736383-53c08700-bc1d-11e8-8feb-43502dec0c85.png)

And within those 163 iframes, there are about 128 of them from the same provider (spdmg-backend2.i-mobile.co.jp).
![image](https://user-images.githubusercontent.com/17778751/45736459-9c784000-bc1d-11e8-92eb-60565b5e41a0.png)

But we only need one iframe among them to enjoy the game. By inspection via Chrome's task manager, those iframes from spdmg-backend2.i-mobile.co.jp can take almost the same amount of memory as KanColle iframe. We all know that there is memory leak of KanColle related to audio management since 2.0. But if we set the in-game audio muted, the memory consumed by those iframes from spdmg-backend2.i-mobile.co.jp can be even more than KanColle.

I'm not sure non-default-white mode of your widget can really save those memory or not; however from my inspection in the Chrome console and it seemed to work (no ads, YEH!!!). And the error logged in non-default-white mode caught my eyes, which made me concern about the legality of this mode.

Will KanColle or DMM notice that we are using in this mode?
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.dmm.com') does not match the recipient window's origin ('http://osapi.dmm.com').
postMessage @ ifr?synd=dmm&container=dmm&owner=14722939&viewer=14722939&aid=854854&mid=21399328&country=jp&lang=ja&view=canvas&parent=http%3A%2F%2Fwww.dmm.com%2Fnetgame%2Fsocial%2F&url=http%3A%2F%2F203.104.209.7%2Fgadget_html5.xml&st=r%2FtxnMipdIjTKTngc9oXkk%2FHn%2BL%2FKJcXBYqO7RG%2BaOk85gkNh4j3kjYX4D11ciVnUJdtAdhjjgPz0UyxZgU7mBUFsewnyPkAE3LQa6H3qUrBPjsbIWny6Rshea8VQclCOItUm0k3cwlshVLeDWUKzj0UP1Pn7kOnCkjwcJE6H%2FY%2F4p1f3mt9aHDrtU%2FZfwGyCzcZxTMoPN0Mh8Pebnz3InlT0og%3D:187

```

I will be appreciate if there is your feedback. Thank you :)

Best Regards,
MomoCow

**Comment by otiai10** [comment]
Since conversation in the group is more in Japanese than I expected, if it's annoying for you, feel free to leave the group.

Thank you anyway for joining v3 testing

**Comment by momocow** [comment]
Thanks for inviting me, and don't worry, the language won't get me annoyed thanks to years of experience in Japanese games and anime's. 😂 Though I cannot speak and write well in Japanese but I can read and listen.

If one day I leave the group, there is nothing wrong with Japanese. ;)

お互い、頑張りましょうね 🎉
